import { MENU_ICONES_DST } from "@/data/menu-estrutura-dst-gerado";

/** Overrides de icones para alinhamento visual do produto. */
const ICONE_MENU_OVERRIDES: Record<string, string> = {
  "infotime-template-app": "pi-cog",
  dashboard: "pi-sliders-h",
  "cad-acesso-usuário": "pi-users",
  "cadastros-clientes": "pi-users",
  "cad-estoque-fornecedores-fabricantes": "pi-user-plus",
  cadastros: "pi-cog",
  "infotime-cad-acessos": "pi-key",
  "infotime-cad-comercial": "pi-briefcase",
  "infotime-cad-com-canais-cliente": "pi-share-alt",
  "infotime-cad-com-categorias-produto": "pi-tags",
  "infotime-cad-com-concorrentes": "pi-users",
  "infotime-cad-com-dimensoes": "pi-arrows-h",
  "infotime-cad-com-fases": "pi-flag",
  "infotime-cad-com-mensagens": "pi-envelope",
  "infotime-cad-com-motivos-perda": "pi-times-circle",
  "infotime-cad-com-produtos-servicos": "pi-box",
  "infotime-cad-com-tipos-contrato": "pi-file",
  "infotime-cad-com-tipos-negocio": "pi-briefcase",
  "infotime-cad-config-gerais": "pi-cog",
  "infotime-cad-financeiro": "pi-wallet",
  "infotime-cad-fin-agencias": "pi-building-columns",
  "infotime-cad-fin-bancos": "pi-building",
  "infotime-cad-fin-centro-custo": "pi-sitemap",
  "infotime-cad-fin-contas-caixa": "pi-wallet",
  "infotime-cad-fin-regioes-estaduais": "pi-map",
  "infotime-cad-fin-tipos-cliente": "pi-users",
  "infotime-cad-fin-tipos-documento": "pi-file-pdf",
  "infotime-cad-integracao": "pi-link",
  "infotime-cad-int-codigo-externo": "pi-external-link",
  "infotime-cad-int-config-cobranca": "pi-handshake",
  "infotime-cad-int-tipos-especie": "pi-tag",
  "infotime-cad-int-demais-lab": "pi-sitemap",
  "infotime-cad-pessoal": "pi-id-card",
  "infotime-cad-pess-situacoes-colaborador": "pi-info-circle",
  "infotime-cad-pess-tipos-colaborador": "pi-user-plus",
  "infotime-cad-pess-tipos-despesa-viagem": "pi-money-bill",
  "infotime-cad-pess-tipos-finalidade-viagem": "pi-map-marker",
  "infotime-cad-pess-tipos-meio-transporte": "pi-truck",
  "infotime-cad-pessoal-demais-dst": "pi-folder-open",
  "infotime-cad-site-noticias-infotime": "pi-book",
  "infotime-cad-site-portal": "pi-globe",
  "infotime-cad-site-treinamentos": "pi-desktop",
  "infotime-cad-suporte": "pi-wrench",
  "infotime-cad-sup-aplicacoes": "pi-th-large",
  "infotime-cad-sup-triggers-auditoria": "pi-cog",
  "infotime-cad-sup-sincronizar-grupos-apps": "pi-refresh",
  "infotime-comercial": "pi-briefcase",
  "infotime-comercial-clientes-congresso": "pi-users",
  "infotime-comercial-demais-faturamento": "pi-folder-open",
  "infotime-comercial-demais-recepcao": "pi-inbox",
  "infotime-comercial-implantacoes": "pi-wrench",
  "infotime-comercial-impl-em-andamento": "pi-play",
  "infotime-comercial-impl-pausadas": "pi-ban",
  "infotime-comercial-impl-realizadas": "pi-check-circle",
  "infotime-comercial-impl-tarefas": "pi-list-check",
  "infotime-comercial-impl-tarefas-por-solucao": "pi-sitemap",
  "infotime-comercial-negociacoes": "pi-comments",
  "infotime-comercial-negociacoes-tarefa": "pi-clock",
  "infotime-comercial-pesquisas-satisfacao": "pi-star",
  "infotime-comercial-pipeline": "pi-chart-line",
  "infotime-comercial-propostas": "pi-file-edit",
  "infotime-complemento-sistema": "pi-sitemap",
  "infotime-estoque": "pi-th-large",
  "infotime-estoque-demais": "pi-list",
  "infotime-fin-contas-pagar": "pi-minus-circle",
  "infotime-fin-contas-receber": "pi-plus-circle",
  "infotime-fin-demais-cadastro": "pi-book",
  "infotime-fin-demais-modulo": "pi-folder",
  "infotime-fin-fat-aniversarios-contrato": "pi-calendar",
  "infotime-fin-fat-boletos": "pi-ticket",
  "infotime-fin-fat-licencas": "pi-id-card",
  "infotime-fin-fechamento": "pi-lock",
  "infotime-fin-grupo-faturamento": "pi-file",
  "infotime-financeiro": "pi-dollar",
  "infotime-modulos-operacionais": "pi-box",
  "infotime-rh": "pi-users",
  "infotime-rh-classificacao-cargo": "pi-briefcase",
  "infotime-rh-motivos-reajuste": "pi-percentage",
  "infotime-rh-niveis-classificacao-cargos": "pi-sort-alt",
  "infotime-rh-pop-documentos": "pi-file",
  "infotime-rh-tarefas-colaborador": "pi-list-check",
  "solucoes-saude-humana": "pi-heart",
  "solucoes-saude-humana-novo-atendimento": "pi-heart",
  /** DST gerado usa pi-circle — substituição visual até regenerar o menu. */
  "cadastros-soroteca-aliquota": "pi-percentage",
  "cad-exames-medicamento": "pi-heart",
  "mod-controle-de-qualidade-analitos": "pi-search",
};

/** Ícones dos cadastros já existentes na web (PrimeIcons). */
const ICONE_MENU_LEGADO: Record<string, string> = {
  dashboard: "pi-home",
  relatorios: "pi-chart-bar",
  "relatorios-tipos": "pi-file-pdf",
  ajuda: "pi-question-circle",
  "ajuda-documentacao": "pi-book",
  "ajuda-suporte": "pi-comments",
  cadastros: "pi-folder",
  "cadastros-clientes": "pi-users",
  "cadastros-medicos": "pi-user-plus",
  "cadastros-grupo-clientes": "pi-users",
  "cadastros-grupo-medicos": "pi-user-plus",
  "cadastros-grupo-pagamentos": "pi-credit-card",
  "cadastros-grupo-laboratorio": "pi-box",
  "cadastros-grupo-agenda": "pi-calendar",
  "cadastros-grupo-sistema": "pi-cog",
  "cadastros-grupo-convenios-exames": "pi-briefcase",
  "cadastros-grupo-estoque": "pi-box",
  "cadastros-grupo-relatorios": "pi-file-pdf",
  "cadastros-cbo": "pi-briefcase",
  "cadastros-cid": "pi-book",
  "cadastros-conselho-regional": "pi-shield",
  "cadastros-especialidade-medica": "pi-star",
  "cadastros-etnia": "pi-globe",
  "cadastros-feriado": "pi-calendar",
  "cadastros-motivo-cancelamento": "pi-times-circle",
  "cadastros-motivo-desconto": "pi-percentage",
  "cadastros-motivo-exame-retificacao": "pi-pencil",
  "cadastros-motivo-orcamento-rejeicao": "pi-ban",
  "cadastros-motivo-quarentena": "pi-lock",
  "cadastros-motivo-recoleta": "pi-refresh",
  "cadastros-motivo-retificacao": "pi-file-edit",
  "cadastros-raca": "pi-flag",
  "cadastros-situacao-coleta": "pi-map-marker",
  "cadastros-tipo-aplicacao": "pi-box",
  "cadastros-tipo-destino-resultado": "pi-send",
  "cadastros-tipo-estado-civil": "pi-heart",
  "cadastros-tipo-evento": "pi-bolt",
  "cadastros-tipo-indicacao": "pi-share-alt",
  "cadastros-tipo-integracao": "pi-link",
  "cadastros-tipo-interface": "pi-desktop",
  "cadastros-tipo-pagamento": "pi-credit-card",
  "cadastros-preco-tabela": "pi-table",
  "cadastros-preco-fator": "pi-calculator",
  "cadastros-tipo-relatorio": "pi-file-pdf",
  "cadastros-unidade-federacao": "pi-map",
  "cadastros-analisadores": "pi-desktop",
  "cadastros-aplicacoes": "pi-th-large",
  "cadastros-computadores": "pi-desktop",
  "cadastros-convenios": "pi-id-card",
  "cadastros-exames": "pi-file",
  "cadastros-exames-material-lab-apoio": "pi-link",
  "cadastros-grupos": "pi-sitemap",
  "cadastros-indicacoes": "pi-share-alt",
  "cadastros-integracoes": "pi-link",
  "cadastros-labs-apoio": "pi-building",
  "cadastros-labs-apoio-unidade": "pi-sitemap",
  "cadastros-labs-apoio-ws": "pi-wifi",
  "cadastros-locais-armazenamento": "pi-folder-open",
  "cadastros-materiais": "pi-box",
  "cadastros-medicamentos": "pi-heart",
  "cadastros-modelos-resultado": "pi-file-edit",
  "cadastros-procedencias": "pi-map-marker",
  "cadastros-questionarios": "pi-list-check",
  "cadastros-recipientes": "pi-inbox",
  "cadastros-setores": "pi-th-large",
  "cadastros-usuarios": "pi-user",
  preferencias: "pi-sliders-h",
  "preferencias-formularios": "pi-table",
  "preferencias-layout-formulario": "pi-objects-column",
  solucoes: "pi-th-large",
  "solucoes-saude-humana": "pi-heart",
};

/** Ícone PrimeIcons por id de menu (DST + legado). */
export function iconeMenuItem(id: string): string {
  return (
    ICONE_MENU_OVERRIDES[id] ?? MENU_ICONES_DST[id] ?? ICONE_MENU_LEGADO[id] ?? "pi-circle"
  );
}

/**
 * @deprecated Use `iconeMenuItem(id)` para ids novos do DST.
 * Objeto parcial para código legado que espera indexação direta.
 */
export const ICONE_MENU_ITEM: Record<string, string> = new Proxy(
  {} as Record<string, string>,
  {
    get(_, prop: string) {
      return iconeMenuItem(prop);
    },
  },
);
