import type { LigaColunaListagem } from "@/components/formulario-pesquisa/liga-listagem.types";

/** Colunas alinhadas ao SQL legado Cliente_Lst e ao payload `ClienteListaItemDto` da API. */
export const CLIENTE_INFOTIME_COLUNAS_LISTAGEM: LigaColunaListagem[] = [
  {
    campo: "nomeFantasia",
    cabecalho: "Cliente",
    ordenavel: true,
    pesquisaServidor: true,
    campoConsulta: "nomeFantasia",
    visivelPadrao: true,
    filtroRefinado: { tipo: "texto" },
    fixo: true,
  },
  {
    campo: "razaoSocial",
    cabecalho: "Razão social / nome",
    ordenavel: true,
    pesquisaServidor: true,
    campoConsulta: "razaoSocial",
    visivelPadrao: false,
    filtroRefinado: { tipo: "texto" },
  },
  {
    campo: "tipoPessoa",
    cabecalho: "Tipo pessoa",
    ordenavel: true,
    pesquisaServidor: true,
    campoConsulta: "tipoPessoa",
    visivelPadrao: false,
    filtroRefinado: { tipo: "texto" },
  },
  {
    campo: "cnpj",
    cabecalho: "CNPJ / CPF",
    ordenavel: true,
    pesquisaServidor: true,
    campoConsulta: "cnpj",
    mascaraBuscaServidor: "cnpj",
    visivelPadrao: true,
    filtroRefinado: { tipo: "texto" },
  },
  {
    campo: "cidade",
    cabecalho: "Cidade",
    ordenavel: true,
    pesquisaServidor: true,
    campoConsulta: "cidade",
    visivelPadrao: true,
    filtroRefinado: { tipo: "texto" },
  },
  {
    campo: "estado",
    cabecalho: "UF",
    ordenavel: true,
    pesquisaServidor: true,
    campoConsulta: "estado",
    visivelPadrao: true,
    filtroRefinado: { tipo: "texto" },
  },
  {
    campo: "telefone",
    cabecalho: "Telefone",
    ordenavel: true,
    pesquisaServidor: true,
    campoConsulta: "telefone",
    mascaraBuscaServidor: "telefone",
    visivelPadrao: true,
    filtroRefinado: { tipo: "texto" },
  },
  {
    campo: "celular",
    cabecalho: "Celular",
    ordenavel: false,
    pesquisaServidor: true,
    campoConsulta: "celular",
    mascaraBuscaServidor: "telefone",
    visivelPadrao: false,
    filtroRefinado: { tipo: "texto" },
  },
  {
    campo: "email",
    cabecalho: "E-mail",
    ordenavel: false,
    pesquisaServidor: true,
    campoConsulta: "email",
    visivelPadrao: false,
    filtroRefinado: { tipo: "texto" },
  },
  {
    campo: "idSituacaoCliente",
    cabecalho: "Situação",
    ordenavel: false,
    visivelPadrao: true,
    filtroRefinado: { tipo: "inteiro" },
    corpoCelula: (linha) =>
      String((linha as Record<string, unknown>).situacaoClienteDescricao ?? "—"),
  },
  {
    campo: "idTipoCliente",
    cabecalho: "Tipo",
    ordenavel: false,
    visivelPadrao: false,
    filtroRefinado: { tipo: "inteiro" },
    corpoCelula: (linha) =>
      String((linha as Record<string, unknown>).tipoClienteDescricao ?? "—"),
  },
  {
    campo: "idClienteCanal",
    cabecalho: "Canal",
    ordenavel: false,
    visivelPadrao: false,
    corpoCelula: (linha) =>
      String((linha as Record<string, unknown>).canalDescricao ?? "—"),
  },
  {
    campo: "contatos",
    cabecalho: "Contatos",
    ordenavel: false,
    visivelPadrao: false,
    quebraLinhaTexto: true,
  },
  {
    campo: "unidades",
    cabecalho: "Unidades",
    ordenavel: false,
    alinhamento: "right",
    visivelPadrao: true,
  },
  {
    campo: "idCliente",
    cabecalho: "Código",
    ordenavel: true,
    pesquisaServidor: true,
    campoConsulta: "idCliente",
    colunaChavePrimaria: true,
    visivelPadrao: false,
    alinhamento: "right",
    larguraMinPx: 88,
  },
];
