-- Fatia C — custo por exame, score de cliente + colunas denormalizadas em infotime_cliente. RLS + GRANTs.

ALTER TABLE public.infotime_cliente
  ADD COLUMN IF NOT EXISTS score_inadimplencia numeric(5, 2) NULL;
ALTER TABLE public.infotime_cliente
  ADD COLUMN IF NOT EXISTS classificacao_score varchar(10) NULL;

CREATE TABLE IF NOT EXISTS public.infotime_exame_custo (
  id_exame_custo int8 GENERATED BY DEFAULT AS IDENTITY (
    INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE
  ) NOT NULL,
  id_tenacidade int8 NOT NULL,
  id_usuario_auditoria int8 NULL,
  codigo_exame varchar(50) NOT NULL,
  descricao_exame varchar(200) NOT NULL,
  custo_reagente numeric(10, 4) NOT NULL DEFAULT 0,
  custo_material numeric(10, 4) NOT NULL DEFAULT 0,
  custo_mao_obra numeric(10, 4) NOT NULL DEFAULT 0,
  custo_total numeric(10, 4) GENERATED ALWAYS AS (custo_reagente + custo_material + custo_mao_obra) STORED,
  competencia_inicio date NOT NULL,
  competencia_fim date NULL,
  data_atualizacao timestamptz NOT NULL DEFAULT now(),
  endereco_ip_auditoria varchar(50) NULL,
  nome_aplicacao_auditoria varchar(255) NULL,
  CONSTRAINT infotime_exame_custo_pkey PRIMARY KEY (id_exame_custo),
  CONSTRAINT fk_infotime_exame_custo_ten FOREIGN KEY (id_tenacidade)
    REFERENCES public.infotime_tenacidade (id_tenacidade) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT fk_infotime_exame_custo_ua FOREIGN KEY (id_usuario_auditoria)
    REFERENCES public.infotime_usuario (id_usuario) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT uq_infotime_exame_custo UNIQUE (id_tenacidade, codigo_exame, competencia_inicio)
);

CREATE INDEX IF NOT EXISTS idx_infotime_exame_custo_tc ON public.infotime_exame_custo (id_tenacidade, codigo_exame);

CREATE TABLE IF NOT EXISTS public.infotime_cliente_score (
  id_cliente_score int8 GENERATED BY DEFAULT AS IDENTITY (
    INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE
  ) NOT NULL,
  id_tenacidade int8 NOT NULL,
  id_cliente int8 NOT NULL,
  id_usuario_auditoria int8 NULL,
  score numeric(5, 2) NOT NULL,
  classificacao varchar(10) NOT NULL,
  dia_medio_atraso numeric(6, 2) NULL,
  percentual_em_atraso numeric(5, 2) NULL,
  qtd_lancamentos_6_meses int4 NULL,
  qtd_atrasados_6_meses int4 NULL,
  valor_total_em_aberto numeric(15, 2) NULL,
  data_calculo timestamptz NOT NULL DEFAULT now(),
  data_proximo_calculo timestamptz NULL,
  endereco_ip_auditoria varchar(50) NULL,
  nome_aplicacao_auditoria varchar(255) NULL,
  CONSTRAINT infotime_cliente_score_pkey PRIMARY KEY (id_cliente_score),
  CONSTRAINT fk_infotime_cli_score_ten FOREIGN KEY (id_tenacidade)
    REFERENCES public.infotime_tenacidade (id_tenacidade) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT fk_infotime_cli_score_cli FOREIGN KEY (id_cliente)
    REFERENCES public.infotime_cliente (id_cliente) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT fk_infotime_cli_score_ua FOREIGN KEY (id_usuario_auditoria)
    REFERENCES public.infotime_usuario (id_usuario) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT uq_infotime_cli_score UNIQUE (id_tenacidade, id_cliente)
);

CREATE INDEX IF NOT EXISTS idx_infotime_cli_score_class ON public.infotime_cliente_score (id_tenacidade, classificacao);

DO $$
DECLARE
  tbl text;
  r regclass;
BEGIN
  FOREACH tbl IN ARRAY ARRAY['infotime_exame_custo', 'infotime_cliente_score']
  LOOP
    IF to_regclass('public.' || quote_ident(tbl)) IS NULL THEN
      CONTINUE;
    END IF;
    r := ('public.' || tbl)::regclass;
    EXECUTE format('ALTER TABLE %s ENABLE ROW LEVEL SECURITY', r);
    EXECUTE format('ALTER TABLE %s FORCE ROW LEVEL SECURITY', r);
    EXECUTE format('DROP POLICY IF EXISTS %I ON %s', tbl || '_tenant_rls', r);
    EXECUTE format(
      $exec$
      CREATE POLICY %I ON %s
      FOR ALL
      USING (
        NULLIF(current_setting('app.current_tenant_id', true), '') IS NOT NULL
        AND id_tenacidade = (NULLIF(current_setting('app.current_tenant_id', true), ''))::bigint
      )
      WITH CHECK (
        NULLIF(current_setting('app.current_tenant_id', true), '') IS NOT NULL
        AND id_tenacidade = (NULLIF(current_setting('app.current_tenant_id', true), ''))::bigint
      )
      $exec$,
      tbl || '_tenant_rls',
      r
    );
  END LOOP;
END $$;

DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'LigaDev') THEN
    EXECUTE 'GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO "LigaDev"';
    EXECUTE 'GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO "LigaDev"';
  END IF;
  IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'liga_infolab_rw') THEN
    EXECUTE 'GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO liga_infolab_rw';
    EXECUTE 'GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO liga_infolab_rw';
  END IF;
END $$;
