-- Fatia D — extrato bancário + PIX (exige infotime_conta_caixa). RLS + GRANTs.

DO $$
BEGIN
  IF to_regclass('public.infotime_conta_caixa') IS NULL THEN
    RAISE EXCEPTION 'infotime_conta_caixa ausente — aplicar baseline/renomes antes da fatia D.';
  END IF;
  EXECUTE 'ALTER TABLE public.infotime_conta_caixa ADD COLUMN IF NOT EXISTS compoe_saldo_dfc bpchar(1) NOT NULL DEFAULT ''S''';
END $$;

CREATE TABLE IF NOT EXISTS public.infotime_extrato_bancario_lote (
  id_extrato_bancario_lote int8 GENERATED BY DEFAULT AS IDENTITY (
    INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE
  ) NOT NULL,
  id_tenacidade int8 NOT NULL,
  id_conta_caixa int8 NOT NULL,
  id_usuario_auditoria int8 NULL,
  data_importacao timestamptz NOT NULL DEFAULT now(),
  nome_arquivo varchar(255) NULL,
  formato_arquivo varchar(10) NOT NULL,
  data_inicio_periodo date NOT NULL,
  data_fim_periodo date NOT NULL,
  total_creditos numeric(15, 2) NULL,
  total_debitos numeric(15, 2) NULL,
  qtd_movimentos int4 NULL,
  id_usuario_importacao int8 NULL,
  endereco_ip_auditoria varchar(50) NULL,
  nome_aplicacao_auditoria varchar(255) NULL,
  CONSTRAINT infotime_extrato_lote_pkey PRIMARY KEY (id_extrato_bancario_lote),
  CONSTRAINT fk_infotime_ext_lt_ten FOREIGN KEY (id_tenacidade)
    REFERENCES public.infotime_tenacidade (id_tenacidade) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT fk_infotime_ext_lt_cc FOREIGN KEY (id_conta_caixa)
    REFERENCES public.infotime_conta_caixa (id_conta_caixa) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT fk_infotime_ext_lt_ua FOREIGN KEY (id_usuario_auditoria)
    REFERENCES public.infotime_usuario (id_usuario) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT fk_infotime_ext_lt_ui FOREIGN KEY (id_usuario_importacao)
    REFERENCES public.infotime_usuario (id_usuario) ON DELETE RESTRICT ON UPDATE RESTRICT
);

CREATE TABLE IF NOT EXISTS public.infotime_extrato_bancario_linha (
  id_extrato_bancario_linha int8 GENERATED BY DEFAULT AS IDENTITY (
    INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE
  ) NOT NULL,
  id_tenacidade int8 NOT NULL,
  id_extrato_bancario_lote int8 NOT NULL,
  id_usuario_auditoria int8 NULL,
  data_movimento date NOT NULL,
  valor numeric(15, 2) NOT NULL,
  tipo varchar(10) NOT NULL,
  historico_banco varchar(500) NULL,
  numero_documento_banco varchar(100) NULL,
  cnpj_contraparte varchar(18) NULL,
  status_conciliacao varchar(20) NOT NULL DEFAULT 'PENDENTE',
  id_lancamento_receita int8 NULL,
  id_lancamento_despesa int8 NULL,
  confidencia_match numeric(5, 2) NULL,
  data_conciliacao timestamptz NULL,
  id_usuario_conciliacao int8 NULL,
  endereco_ip_auditoria varchar(50) NULL,
  nome_aplicacao_auditoria varchar(255) NULL,
  CONSTRAINT infotime_extrato_linha_pkey PRIMARY KEY (id_extrato_bancario_linha),
  CONSTRAINT fk_infotime_ext_ln_ten FOREIGN KEY (id_tenacidade)
    REFERENCES public.infotime_tenacidade (id_tenacidade) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT fk_infotime_ext_ln_lote FOREIGN KEY (id_extrato_bancario_lote)
    REFERENCES public.infotime_extrato_bancario_lote (id_extrato_bancario_lote) ON DELETE CASCADE ON UPDATE RESTRICT,
  CONSTRAINT fk_infotime_ext_ln_ua FOREIGN KEY (id_usuario_auditoria)
    REFERENCES public.infotime_usuario (id_usuario) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT fk_infotime_ext_ln_lr FOREIGN KEY (id_lancamento_receita)
    REFERENCES public.infotime_lancamento_receita (id_lancamento_receita) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT fk_infotime_ext_ln_ld FOREIGN KEY (id_lancamento_despesa)
    REFERENCES public.infotime_lancamento_despesa (id_lancamento_despesa) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT fk_infotime_ext_ln_uc FOREIGN KEY (id_usuario_conciliacao)
    REFERENCES public.infotime_usuario (id_usuario) ON DELETE RESTRICT ON UPDATE RESTRICT
);

CREATE INDEX IF NOT EXISTS idx_infotime_ext_ln_st ON public.infotime_extrato_bancario_linha (status_conciliacao);
CREATE INDEX IF NOT EXISTS idx_infotime_ext_ln_dt ON public.infotime_extrato_bancario_linha (data_movimento);

CREATE TABLE IF NOT EXISTS public.infotime_pix_configuracao (
  id_pix_configuracao int8 GENERATED BY DEFAULT AS IDENTITY (
    INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE
  ) NOT NULL,
  id_tenacidade int8 NOT NULL,
  id_conta_caixa int8 NOT NULL,
  id_usuario_auditoria int8 NULL,
  ambiente varchar(10) NOT NULL,
  client_id varchar(255) NOT NULL,
  client_secret_encrypted text NOT NULL,
  chave_pix varchar(100) NOT NULL,
  banco varchar(50) NOT NULL,
  certificado_pem text NULL,
  ativo bpchar(1) NOT NULL DEFAULT 'S',
  data_cadastro timestamptz NOT NULL DEFAULT now(),
  endereco_ip_auditoria varchar(50) NULL,
  nome_aplicacao_auditoria varchar(255) NULL,
  CONSTRAINT infotime_pix_cfg_pkey PRIMARY KEY (id_pix_configuracao),
  CONSTRAINT fk_infotime_pix_cfg_ten FOREIGN KEY (id_tenacidade)
    REFERENCES public.infotime_tenacidade (id_tenacidade) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT fk_infotime_pix_cfg_cc FOREIGN KEY (id_conta_caixa)
    REFERENCES public.infotime_conta_caixa (id_conta_caixa) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT fk_infotime_pix_cfg_ua FOREIGN KEY (id_usuario_auditoria)
    REFERENCES public.infotime_usuario (id_usuario) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT uq_infotime_pix_cfg UNIQUE (id_tenacidade, id_conta_caixa)
);

CREATE TABLE IF NOT EXISTS public.infotime_pix_cobranca (
  id_pix_cobranca int8 GENERATED BY DEFAULT AS IDENTITY (
    INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE
  ) NOT NULL,
  id_tenacidade int8 NOT NULL,
  id_lancamento_receita int8 NULL,
  id_pix_configuracao int8 NOT NULL,
  id_usuario_auditoria int8 NULL,
  tx_id varchar(35) NOT NULL,
  e2e_id varchar(32) NULL,
  valor numeric(15, 2) NOT NULL,
  status varchar(30) NOT NULL DEFAULT 'ATIVA',
  qr_code_payload text NULL,
  qr_code_imagem_base64 text NULL,
  data_criacao timestamptz NOT NULL DEFAULT now(),
  data_vencimento date NULL,
  data_pagamento timestamptz NULL,
  valor_pago numeric(15, 2) NULL,
  cnpj_pagador varchar(18) NULL,
  nome_pagador varchar(200) NULL,
  info_pagador text NULL,
  webhook_payload jsonb NULL,
  endereco_ip_auditoria varchar(50) NULL,
  nome_aplicacao_auditoria varchar(255) NULL,
  CONSTRAINT infotime_pix_cob_pkey PRIMARY KEY (id_pix_cobranca),
  CONSTRAINT fk_infotime_pix_cob_ten FOREIGN KEY (id_tenacidade)
    REFERENCES public.infotime_tenacidade (id_tenacidade) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT fk_infotime_pix_cob_lr FOREIGN KEY (id_lancamento_receita)
    REFERENCES public.infotime_lancamento_receita (id_lancamento_receita) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT fk_infotime_pix_cob_cfg FOREIGN KEY (id_pix_configuracao)
    REFERENCES public.infotime_pix_configuracao (id_pix_configuracao) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT fk_infotime_pix_cob_ua FOREIGN KEY (id_usuario_auditoria)
    REFERENCES public.infotime_usuario (id_usuario) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT uq_infotime_pix_cob_tx UNIQUE (tx_id)
);

CREATE INDEX IF NOT EXISTS idx_infotime_pix_cob_st ON public.infotime_pix_cobranca (status);

DO $$
DECLARE
  tbl text;
  r regclass;
BEGIN
  FOREACH tbl IN ARRAY ARRAY[
    'infotime_extrato_bancario_lote',
    'infotime_extrato_bancario_linha',
    'infotime_pix_configuracao',
    'infotime_pix_cobranca'
  ]
  LOOP
    IF to_regclass('public.' || quote_ident(tbl)) IS NULL THEN
      CONTINUE;
    END IF;
    r := ('public.' || tbl)::regclass;
    EXECUTE format('ALTER TABLE %s ENABLE ROW LEVEL SECURITY', r);
    EXECUTE format('ALTER TABLE %s FORCE ROW LEVEL SECURITY', r);
    EXECUTE format('DROP POLICY IF EXISTS %I ON %s', tbl || '_tenant_rls', r);
    EXECUTE format(
      $exec$
      CREATE POLICY %I ON %s
      FOR ALL
      USING (
        NULLIF(current_setting('app.current_tenant_id', true), '') IS NOT NULL
        AND id_tenacidade = (NULLIF(current_setting('app.current_tenant_id', true), ''))::bigint
      )
      WITH CHECK (
        NULLIF(current_setting('app.current_tenant_id', true), '') IS NOT NULL
        AND id_tenacidade = (NULLIF(current_setting('app.current_tenant_id', true), ''))::bigint
      )
      $exec$,
      tbl || '_tenant_rls',
      r
    );
  END LOOP;
END $$;

DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'LigaDev') THEN
    EXECUTE 'GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO "LigaDev"';
    EXECUTE 'GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO "LigaDev"';
  END IF;
  IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'liga_infolab_rw') THEN
    EXECUTE 'GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO liga_infolab_rw';
    EXECUTE 'GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO liga_infolab_rw';
  END IF;
END $$;
