-- Fatia B — régua de cobrança + RLS + GRANTs. Idempotente (IF NOT EXISTS).

CREATE TABLE IF NOT EXISTS public.infotime_regua_cobranca (
  id_regua_cobranca int8 GENERATED BY DEFAULT AS IDENTITY (
    INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE
  ) NOT NULL,
  id_tenacidade int8 NOT NULL,
  id_usuario_auditoria int8 NULL,
  descricao varchar(100) NOT NULL,
  ativo bpchar(1) NOT NULL DEFAULT 'S',
  data_criacao timestamptz NOT NULL DEFAULT now(),
  endereco_ip_auditoria varchar(50) NULL,
  nome_aplicacao_auditoria varchar(255) NULL,
  CONSTRAINT infotime_regua_cobranca_pkey PRIMARY KEY (id_regua_cobranca),
  CONSTRAINT fk_infotime_regua_cb_ten FOREIGN KEY (id_tenacidade)
    REFERENCES public.infotime_tenacidade (id_tenacidade) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT fk_infotime_regua_cb_ua FOREIGN KEY (id_usuario_auditoria)
    REFERENCES public.infotime_usuario (id_usuario) ON DELETE RESTRICT ON UPDATE RESTRICT
);

CREATE TABLE IF NOT EXISTS public.infotime_regua_cobranca_etapa (
  id_regua_cobranca_etapa int8 GENERATED BY DEFAULT AS IDENTITY (
    INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE
  ) NOT NULL,
  id_tenacidade int8 NOT NULL,
  id_regua_cobranca int8 NOT NULL,
  id_usuario_auditoria int8 NULL,
  dias_apos_vencimento int4 NOT NULL,
  canal varchar(20) NOT NULL,
  assunto varchar(200) NULL,
  mensagem text NOT NULL,
  ativo bpchar(1) NOT NULL DEFAULT 'S',
  ordem int4 NOT NULL,
  endereco_ip_auditoria varchar(50) NULL,
  nome_aplicacao_auditoria varchar(255) NULL,
  CONSTRAINT infotime_regua_cobranca_etapa_pkey PRIMARY KEY (id_regua_cobranca_etapa),
  CONSTRAINT fk_infotime_regua_et_regua FOREIGN KEY (id_regua_cobranca)
    REFERENCES public.infotime_regua_cobranca (id_regua_cobranca) ON DELETE CASCADE ON UPDATE RESTRICT,
  CONSTRAINT fk_infotime_regua_et_ten FOREIGN KEY (id_tenacidade)
    REFERENCES public.infotime_tenacidade (id_tenacidade) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT fk_infotime_regua_et_ua FOREIGN KEY (id_usuario_auditoria)
    REFERENCES public.infotime_usuario (id_usuario) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT uq_infotime_regua_etapa UNIQUE (id_regua_cobranca, dias_apos_vencimento, canal)
);

CREATE TABLE IF NOT EXISTS public.infotime_regua_cobranca_regra (
  id_regua_cobranca_regra int8 GENERATED BY DEFAULT AS IDENTITY (
    INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE
  ) NOT NULL,
  id_tenacidade int8 NOT NULL,
  id_regua_cobranca int8 NOT NULL,
  id_tipo_agente int8 NULL,
  id_cliente int8 NULL,
  id_usuario_auditoria int8 NULL,
  valor_minimo numeric(15, 2) NOT NULL DEFAULT 0,
  prioridade int4 NOT NULL DEFAULT 1,
  endereco_ip_auditoria varchar(50) NULL,
  nome_aplicacao_auditoria varchar(255) NULL,
  CONSTRAINT infotime_regua_cobranca_regra_pkey PRIMARY KEY (id_regua_cobranca_regra),
  CONSTRAINT fk_infotime_regua_rg_regua FOREIGN KEY (id_regua_cobranca)
    REFERENCES public.infotime_regua_cobranca (id_regua_cobranca) ON DELETE CASCADE ON UPDATE RESTRICT,
  CONSTRAINT fk_infotime_regua_rg_ten FOREIGN KEY (id_tenacidade)
    REFERENCES public.infotime_tenacidade (id_tenacidade) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT fk_infotime_regua_rg_ta FOREIGN KEY (id_tipo_agente)
    REFERENCES public.infotime_tipo_agente (id_tipo_agente) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT fk_infotime_regua_rg_cli FOREIGN KEY (id_cliente)
    REFERENCES public.infotime_cliente (id_cliente) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT fk_infotime_regua_rg_ua FOREIGN KEY (id_usuario_auditoria)
    REFERENCES public.infotime_usuario (id_usuario) ON DELETE RESTRICT ON UPDATE RESTRICT
);

CREATE TABLE IF NOT EXISTS public.infotime_regua_cobranca_envio (
  id_regua_cobranca_envio int8 GENERATED BY DEFAULT AS IDENTITY (
    INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE
  ) NOT NULL,
  id_tenacidade int8 NOT NULL,
  id_lancamento_receita int8 NOT NULL,
  id_regua_cobranca_etapa int8 NOT NULL,
  id_usuario_auditoria int8 NULL,
  data_envio timestamptz NOT NULL DEFAULT now(),
  status_envio varchar(20) NOT NULL DEFAULT 'ENVIADO',
  destinatario varchar(200) NULL,
  resposta_api text NULL,
  tentativas int4 NOT NULL DEFAULT 1,
  endereco_ip_auditoria varchar(50) NULL,
  nome_aplicacao_auditoria varchar(255) NULL,
  CONSTRAINT infotime_regua_cobranca_envio_pkey PRIMARY KEY (id_regua_cobranca_envio),
  CONSTRAINT fk_infotime_regua_ev_ten FOREIGN KEY (id_tenacidade)
    REFERENCES public.infotime_tenacidade (id_tenacidade) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT fk_infotime_regua_ev_lr FOREIGN KEY (id_lancamento_receita)
    REFERENCES public.infotime_lancamento_receita (id_lancamento_receita) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT fk_infotime_regua_ev_et FOREIGN KEY (id_regua_cobranca_etapa)
    REFERENCES public.infotime_regua_cobranca_etapa (id_regua_cobranca_etapa) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT fk_infotime_regua_ev_ua FOREIGN KEY (id_usuario_auditoria)
    REFERENCES public.infotime_usuario (id_usuario) ON DELETE RESTRICT ON UPDATE RESTRICT
);

CREATE INDEX IF NOT EXISTS idx_infotime_regua_env_lr ON public.infotime_regua_cobranca_envio (id_lancamento_receita);
CREATE INDEX IF NOT EXISTS idx_infotime_regua_env_dt ON public.infotime_regua_cobranca_envio (data_envio DESC);
CREATE INDEX IF NOT EXISTS idx_infotime_regua_env_st ON public.infotime_regua_cobranca_envio (status_envio);

DO $$
DECLARE
  tbl text;
  r regclass;
BEGIN
  FOREACH tbl IN ARRAY ARRAY[
    'infotime_regua_cobranca',
    'infotime_regua_cobranca_etapa',
    'infotime_regua_cobranca_regra',
    'infotime_regua_cobranca_envio'
  ]
  LOOP
    IF to_regclass('public.' || quote_ident(tbl)) IS NULL THEN
      CONTINUE;
    END IF;
    r := ('public.' || tbl)::regclass;
    EXECUTE format('ALTER TABLE %s ENABLE ROW LEVEL SECURITY', r);
    EXECUTE format('ALTER TABLE %s FORCE ROW LEVEL SECURITY', r);
    EXECUTE format('DROP POLICY IF EXISTS %I ON %s', tbl || '_tenant_rls', r);
    EXECUTE format(
      $exec$
      CREATE POLICY %I ON %s
      FOR ALL
      USING (
        NULLIF(current_setting('app.current_tenant_id', true), '') IS NOT NULL
        AND id_tenacidade = (NULLIF(current_setting('app.current_tenant_id', true), ''))::bigint
      )
      WITH CHECK (
        NULLIF(current_setting('app.current_tenant_id', true), '') IS NOT NULL
        AND id_tenacidade = (NULLIF(current_setting('app.current_tenant_id', true), ''))::bigint
      )
      $exec$,
      tbl || '_tenant_rls',
      r
    );
  END LOOP;
END $$;

DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'LigaDev') THEN
    EXECUTE 'GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO "LigaDev"';
    EXECUTE 'GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO "LigaDev"';
  END IF;
  IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'liga_infolab_rw') THEN
    EXECUTE 'GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO liga_infolab_rw';
    EXECUTE 'GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO liga_infolab_rw';
  END IF;
END $$;
