ALTER TABLE public.infolab_usuario
ADD COLUMN IF NOT EXISTS id_usuario_perfil bigint;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conname = 'fk_usuario_id_usuario_perfil'
  ) THEN
    ALTER TABLE public.infolab_usuario
    ADD CONSTRAINT fk_usuario_id_usuario_perfil
    FOREIGN KEY (id_usuario_perfil)
    REFERENCES public.infolab_grupo_usuario(id_grupo_usuario)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT;
  END IF;
END
$$;

CREATE TABLE IF NOT EXISTS public.infolab_usuario_perfil (
  id_usuario_perfil bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_grupo_usuario bigint NOT NULL,
  id_formulario bigint NOT NULL,
  id_usuario_auditoria bigint NULL,
  administrador char(1) NOT NULL DEFAULT 'N',
  incluir char(1) NOT NULL DEFAULT 'N',
  editar char(1) NOT NULL DEFAULT 'N',
  excluir char(1) NOT NULL DEFAULT 'N',
  endereco_ip_auditoria varchar(20) NULL,
  nome_aplicacao_auditoria varchar(255) NULL,
  CONSTRAINT ck_usuario_perfil_administrador CHECK (administrador IN ('S', 'N')),
  CONSTRAINT ck_usuario_perfil_incluir CHECK (incluir IN ('S', 'N')),
  CONSTRAINT ck_usuario_perfil_editar CHECK (editar IN ('S', 'N')),
  CONSTRAINT ck_usuario_perfil_excluir CHECK (excluir IN ('S', 'N')),
  CONSTRAINT fk_usuario_perfil_id_grupo_usuario
    FOREIGN KEY (id_grupo_usuario)
    REFERENCES public.infolab_grupo_usuario(id_grupo_usuario)
    ON DELETE CASCADE
    ON UPDATE RESTRICT,
  CONSTRAINT fk_usuario_perfil_id_formulario
    FOREIGN KEY (id_formulario)
    REFERENCES public.infolab_formulario(id_formulario)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT,
  CONSTRAINT fk_usuario_perfil_id_usuario_auditoria
    FOREIGN KEY (id_usuario_auditoria)
    REFERENCES public.infolab_usuario(id_usuario)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT,
  CONSTRAINT uq_usuario_perfil_grupo_formulario
    UNIQUE (id_grupo_usuario, id_formulario)
);

ALTER TABLE public.infolab_usuario_perfil
ADD COLUMN IF NOT EXISTS administrador char(1) NOT NULL DEFAULT 'N';

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conname = 'ck_usuario_perfil_administrador'
  ) THEN
    ALTER TABLE public.infolab_usuario_perfil
    ADD CONSTRAINT ck_usuario_perfil_administrador
    CHECK (administrador IN ('S', 'N'));
  END IF;
END
$$;

CREATE INDEX IF NOT EXISTS idx_usuario_perfil_formulario
  ON public.infolab_usuario_perfil(id_formulario);

CREATE INDEX IF NOT EXISTS idx_usuario_perfil_grupo
  ON public.infolab_usuario_perfil(id_grupo_usuario);
