import { Injectable } from '@nestjs/common';
import { CampoDicionarioDto } from './dto/campo-dicionario.dto';

// [NEGÓCIO] Lê metadados do schema Prisma gerado para expor o dicionário de dados.
// Usado pela tela de configuração de layout para listar campos disponíveis.
@Injectable()
export class DicionarioService {
  // Mapa estático de tabela → campos — atualizado a cada prisma generate
  private readonly metadados: Record<string, CampoDicionarioDto[]> = {
    infolab_cliente: [
      {
        chave: 'id_cliente',
        tipo_banco: 'BigInt',
        nullable: false,
        obrigatorio_sistema: true,
        eh_chave_primaria: true,
        eh_auditoria: false,
        eh_tenant: false,
      },
      {
        chave: 'id_tenacidade',
        tipo_banco: 'BigInt',
        nullable: true,
        obrigatorio_sistema: false,
        eh_chave_primaria: false,
        eh_auditoria: false,
        eh_tenant: true,
      },
      {
        chave: 'nome',
        tipo_banco: 'String',
        nullable: true,
        max_length: 100,
        obrigatorio_sistema: false,
        eh_chave_primaria: false,
        eh_auditoria: false,
        eh_tenant: false,
      },
      {
        chave: 'nome_social',
        tipo_banco: 'String',
        nullable: true,
        max_length: 100,
        obrigatorio_sistema: false,
        eh_chave_primaria: false,
        eh_auditoria: false,
        eh_tenant: false,
      },
      {
        chave: 'cpf',
        tipo_banco: 'String',
        nullable: true,
        max_length: 11,
        obrigatorio_sistema: false,
        eh_chave_primaria: false,
        eh_auditoria: false,
        eh_tenant: false,
      },
      {
        chave: 'documento',
        tipo_banco: 'String',
        nullable: true,
        max_length: 30,
        obrigatorio_sistema: false,
        eh_chave_primaria: false,
        eh_auditoria: false,
        eh_tenant: false,
      },
      {
        chave: 'codigo_passaporte',
        tipo_banco: 'String',
        nullable: true,
        max_length: 20,
        obrigatorio_sistema: false,
        eh_chave_primaria: false,
        eh_auditoria: false,
        eh_tenant: false,
      },
      {
        chave: 'prontuario',
        tipo_banco: 'String',
        nullable: true,
        max_length: 50,
        obrigatorio_sistema: false,
        eh_chave_primaria: false,
        eh_auditoria: false,
        eh_tenant: false,
      },
      {
        chave: 'codigo_externo',
        tipo_banco: 'String',
        nullable: true,
        max_length: 50,
        obrigatorio_sistema: false,
        eh_chave_primaria: false,
        eh_auditoria: false,
        eh_tenant: false,
      },
      {
        chave: 'sexo',
        tipo_banco: 'String',
        nullable: true,
        max_length: 1,
        obrigatorio_sistema: false,
        eh_chave_primaria: false,
        eh_auditoria: false,
        eh_tenant: false,
      },
      {
        chave: 'estado_civil',
        tipo_banco: 'String',
        nullable: true,
        max_length: 1,
        obrigatorio_sistema: false,
        eh_chave_primaria: false,
        eh_auditoria: false,
        eh_tenant: false,
      },
      {
        chave: 'data_nascimento',
        tipo_banco: 'DateTime',
        nullable: true,
        obrigatorio_sistema: false,
        eh_chave_primaria: false,
        eh_auditoria: false,
        eh_tenant: false,
      },
      {
        chave: 'peso',
        tipo_banco: 'BigInt',
        nullable: true,
        obrigatorio_sistema: false,
        eh_chave_primaria: false,
        eh_auditoria: false,
        eh_tenant: false,
      },
      {
        chave: 'altura',
        tipo_banco: 'BigInt',
        nullable: true,
        obrigatorio_sistema: false,
        eh_chave_primaria: false,
        eh_auditoria: false,
        eh_tenant: false,
      },
      {
        chave: 'diabetico',
        tipo_banco: 'String',
        nullable: true,
        max_length: 1,
        obrigatorio_sistema: false,
        eh_chave_primaria: false,
        eh_auditoria: false,
        eh_tenant: false,
      },
      {
        chave: 'falecido',
        tipo_banco: 'String',
        nullable: true,
        max_length: 1,
        obrigatorio_sistema: false,
        eh_chave_primaria: false,
        eh_auditoria: false,
        eh_tenant: false,
      },
      {
        chave: 'receber_mensagem',
        tipo_banco: 'String',
        nullable: true,
        max_length: 1,
        obrigatorio_sistema: false,
        eh_chave_primaria: false,
        eh_auditoria: false,
        eh_tenant: false,
      },
      {
        chave: 'bloqueado',
        tipo_banco: 'String',
        nullable: true,
        max_length: 1,
        obrigatorio_sistema: false,
        eh_chave_primaria: false,
        eh_auditoria: false,
        eh_tenant: false,
      },
      {
        chave: 'cep',
        tipo_banco: 'String',
        nullable: true,
        max_length: 10,
        obrigatorio_sistema: false,
        eh_chave_primaria: false,
        eh_auditoria: false,
        eh_tenant: false,
      },
      {
        chave: 'logradouro',
        tipo_banco: 'String',
        nullable: true,
        max_length: 100,
        obrigatorio_sistema: false,
        eh_chave_primaria: false,
        eh_auditoria: false,
        eh_tenant: false,
      },
      {
        chave: 'numero',
        tipo_banco: 'String',
        nullable: true,
        max_length: 10,
        obrigatorio_sistema: false,
        eh_chave_primaria: false,
        eh_auditoria: false,
        eh_tenant: false,
      },
      {
        chave: 'complemento',
        tipo_banco: 'String',
        nullable: true,
        max_length: 50,
        obrigatorio_sistema: false,
        eh_chave_primaria: false,
        eh_auditoria: false,
        eh_tenant: false,
      },
      {
        chave: 'bairro',
        tipo_banco: 'String',
        nullable: true,
        max_length: 100,
        obrigatorio_sistema: false,
        eh_chave_primaria: false,
        eh_auditoria: false,
        eh_tenant: false,
      },
      {
        chave: 'cidade',
        tipo_banco: 'String',
        nullable: true,
        max_length: 100,
        obrigatorio_sistema: false,
        eh_chave_primaria: false,
        eh_auditoria: false,
        eh_tenant: false,
      },
      {
        chave: 'estado',
        tipo_banco: 'String',
        nullable: true,
        max_length: 2,
        obrigatorio_sistema: false,
        eh_chave_primaria: false,
        eh_auditoria: false,
        eh_tenant: false,
      },
      {
        chave: 'endereco_referencia',
        tipo_banco: 'String',
        nullable: true,
        max_length: 100,
        obrigatorio_sistema: false,
        eh_chave_primaria: false,
        eh_auditoria: false,
        eh_tenant: false,
      },
      {
        chave: 'telefone',
        tipo_banco: 'String',
        nullable: true,
        max_length: 30,
        obrigatorio_sistema: false,
        eh_chave_primaria: false,
        eh_auditoria: false,
        eh_tenant: false,
      },
      {
        chave: 'celular',
        tipo_banco: 'String',
        nullable: true,
        max_length: 30,
        obrigatorio_sistema: false,
        eh_chave_primaria: false,
        eh_auditoria: false,
        eh_tenant: false,
      },
      {
        chave: 'email',
        tipo_banco: 'String',
        nullable: true,
        max_length: 255,
        obrigatorio_sistema: false,
        eh_chave_primaria: false,
        eh_auditoria: false,
        eh_tenant: false,
      },
      {
        chave: 'senha_internet',
        tipo_banco: 'String',
        nullable: true,
        max_length: 255,
        obrigatorio_sistema: false,
        eh_chave_primaria: false,
        eh_auditoria: false,
        eh_tenant: false,
      },
      {
        chave: 'observacao_resultado',
        tipo_banco: 'String',
        nullable: true,
        obrigatorio_sistema: false,
        eh_chave_primaria: false,
        eh_auditoria: false,
        eh_tenant: false,
      },
      {
        chave: 'data_inclusao',
        tipo_banco: 'DateTime',
        nullable: true,
        obrigatorio_sistema: false,
        eh_chave_primaria: false,
        eh_auditoria: true,
        eh_tenant: false,
      },
      {
        chave: 'id_usuario_auditoria',
        tipo_banco: 'BigInt',
        nullable: true,
        obrigatorio_sistema: false,
        eh_chave_primaria: false,
        eh_auditoria: true,
        eh_tenant: false,
      },
      {
        chave: 'endereco_ip_auditoria',
        tipo_banco: 'String',
        nullable: true,
        max_length: 20,
        obrigatorio_sistema: false,
        eh_chave_primaria: false,
        eh_auditoria: true,
        eh_tenant: false,
      },
      {
        chave: 'nome_aplicacao_auditoria',
        tipo_banco: 'String',
        nullable: true,
        max_length: 255,
        obrigatorio_sistema: false,
        eh_chave_primaria: false,
        eh_auditoria: true,
        eh_tenant: false,
      },
    ],
  };

  camposDaTabela(nomeTabela: string): CampoDicionarioDto[] {
    return this.metadados[nomeTabela] ?? [];
  }
}
