import { Injectable } from '@nestjs/common';
import { CampoDicionarioDto } from './dto/campo-dicionario.dto';

/** Metadados mínimos para telas de layout — alinhado ao schema enxuto do template. */
@Injectable()
export class DicionarioService {
  private readonly metadados: Record<string, CampoDicionarioDto[]> = {
    infotime_tenacidade: [
      {
        chave: 'id_tenacidade',
        tipo_banco: 'BigInt',
        nullable: false,
        obrigatorio_sistema: true,
        eh_chave_primaria: true,
        eh_auditoria: false,
        eh_tenant: false,
      },
      {
        chave: 'razao_social',
        tipo_banco: 'String',
        nullable: true,
        max_length: 255,
        obrigatorio_sistema: false,
        eh_chave_primaria: false,
        eh_auditoria: false,
        eh_tenant: false,
      },
      {
        chave: 'nome_fantasia',
        tipo_banco: 'String',
        nullable: true,
        max_length: 255,
        obrigatorio_sistema: false,
        eh_chave_primaria: false,
        eh_auditoria: false,
        eh_tenant: false,
      },
      {
        chave: 'ativo',
        tipo_banco: 'String',
        nullable: true,
        max_length: 1,
        obrigatorio_sistema: false,
        eh_chave_primaria: false,
        eh_auditoria: false,
        eh_tenant: false,
      },
    ],
    infotime_usuario: [
      {
        chave: 'id_usuario',
        tipo_banco: 'BigInt',
        nullable: false,
        obrigatorio_sistema: true,
        eh_chave_primaria: true,
        eh_auditoria: false,
        eh_tenant: false,
      },
      {
        chave: 'id_tenacidade',
        tipo_banco: 'BigInt',
        nullable: true,
        obrigatorio_sistema: false,
        eh_chave_primaria: false,
        eh_auditoria: false,
        eh_tenant: true,
      },
      {
        chave: 'login',
        tipo_banco: 'String',
        nullable: true,
        max_length: 50,
        obrigatorio_sistema: false,
        eh_chave_primaria: false,
        eh_auditoria: false,
        eh_tenant: false,
      },
      {
        chave: 'nome',
        tipo_banco: 'String',
        nullable: true,
        max_length: 100,
        obrigatorio_sistema: false,
        eh_chave_primaria: false,
        eh_auditoria: false,
        eh_tenant: false,
      },
      {
        chave: 'email',
        tipo_banco: 'String',
        nullable: true,
        max_length: 255,
        obrigatorio_sistema: false,
        eh_chave_primaria: false,
        eh_auditoria: false,
        eh_tenant: false,
      },
      {
        chave: 'ativo',
        tipo_banco: 'String',
        nullable: true,
        max_length: 1,
        obrigatorio_sistema: false,
        eh_chave_primaria: false,
        eh_auditoria: false,
        eh_tenant: false,
      },
    ],
    infotime_grupo_usuario: [
      {
        chave: 'id_grupo_usuario',
        tipo_banco: 'BigInt',
        nullable: false,
        obrigatorio_sistema: true,
        eh_chave_primaria: true,
        eh_auditoria: false,
        eh_tenant: false,
      },
      {
        chave: 'id_tenacidade',
        tipo_banco: 'BigInt',
        nullable: false,
        obrigatorio_sistema: true,
        eh_chave_primaria: false,
        eh_auditoria: false,
        eh_tenant: true,
      },
      {
        chave: 'descricao',
        tipo_banco: 'String',
        nullable: true,
        max_length: 200,
        obrigatorio_sistema: false,
        eh_chave_primaria: false,
        eh_auditoria: false,
        eh_tenant: false,
      },
    ],
    infotime_aplicacao: [
      {
        chave: 'id_aplicacao',
        tipo_banco: 'BigInt',
        nullable: false,
        obrigatorio_sistema: true,
        eh_chave_primaria: true,
        eh_auditoria: false,
        eh_tenant: false,
      },
      {
        chave: 'codigo_aplicacao',
        tipo_banco: 'String',
        nullable: false,
        max_length: 120,
        obrigatorio_sistema: true,
        eh_chave_primaria: false,
        eh_auditoria: false,
        eh_tenant: false,
      },
      {
        chave: 'nome_aplicacao',
        tipo_banco: 'String',
        nullable: false,
        max_length: 180,
        obrigatorio_sistema: true,
        eh_chave_primaria: false,
        eh_auditoria: false,
        eh_tenant: false,
      },
      {
        chave: 'nome_tabela_principal',
        tipo_banco: 'String',
        nullable: false,
        max_length: 120,
        obrigatorio_sistema: true,
        eh_chave_primaria: false,
        eh_auditoria: false,
        eh_tenant: false,
      },
    ],
    infotime_aplicacao_campo: [
      {
        chave: 'id_aplicacao_campo',
        tipo_banco: 'BigInt',
        nullable: false,
        obrigatorio_sistema: true,
        eh_chave_primaria: true,
        eh_auditoria: false,
        eh_tenant: false,
      },
      {
        chave: 'codigo_campo',
        tipo_banco: 'String',
        nullable: false,
        max_length: 120,
        obrigatorio_sistema: true,
        eh_chave_primaria: false,
        eh_auditoria: false,
        eh_tenant: false,
      },
      {
        chave: 'nome_campo',
        tipo_banco: 'String',
        nullable: false,
        max_length: 180,
        obrigatorio_sistema: true,
        eh_chave_primaria: false,
        eh_auditoria: false,
        eh_tenant: false,
      },
      {
        chave: 'tipo_componente',
        tipo_banco: 'String',
        nullable: false,
        max_length: 60,
        obrigatorio_sistema: true,
        eh_chave_primaria: false,
        eh_auditoria: false,
        eh_tenant: false,
      },
    ],
    infotime_formulario: [
      {
        chave: 'id_formulario',
        tipo_banco: 'BigInt',
        nullable: false,
        obrigatorio_sistema: true,
        eh_chave_primaria: true,
        eh_auditoria: false,
        eh_tenant: false,
      },
      {
        chave: 'codigo',
        tipo_banco: 'String',
        nullable: false,
        max_length: 80,
        obrigatorio_sistema: true,
        eh_chave_primaria: false,
        eh_auditoria: false,
        eh_tenant: false,
      },
      {
        chave: 'descricao',
        tipo_banco: 'String',
        nullable: true,
        max_length: 255,
        obrigatorio_sistema: false,
        eh_chave_primaria: false,
        eh_auditoria: false,
        eh_tenant: false,
      },
    ],
  };

  camposDaTabela(nomeTabela: string): CampoDicionarioDto[] {
    return this.metadados[nomeTabela] ?? [];
  }
}
