-- Fatia E — portal do convênio (utilizadores externos) + log de acesso. RLS + GRANTs.

CREATE TABLE IF NOT EXISTS public.infotime_portal_usuario (
  id_portal_usuario int8 GENERATED BY DEFAULT AS IDENTITY (
    INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE
  ) NOT NULL,
  id_tenacidade int8 NOT NULL,
  id_cliente int8 NULL,
  id_usuario_auditoria int8 NULL,
  email varchar(200) NOT NULL,
  senha_hash varchar(255) NOT NULL,
  nome_contato varchar(200) NULL,
  ativo bpchar(1) NOT NULL DEFAULT 'S',
  data_cadastro timestamptz NOT NULL DEFAULT now(),
  ultimo_acesso timestamptz NULL,
  token_reset_senha varchar(100) NULL,
  validade_token_reset timestamptz NULL,
  endereco_ip_auditoria varchar(50) NULL,
  nome_aplicacao_auditoria varchar(255) NULL,
  CONSTRAINT infotime_portal_usuario_pkey PRIMARY KEY (id_portal_usuario),
  CONSTRAINT fk_infotime_pu_ten FOREIGN KEY (id_tenacidade)
    REFERENCES public.infotime_tenacidade (id_tenacidade) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT fk_infotime_pu_cli FOREIGN KEY (id_cliente)
    REFERENCES public.infotime_cliente (id_cliente) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT fk_infotime_pu_ua FOREIGN KEY (id_usuario_auditoria)
    REFERENCES public.infotime_usuario (id_usuario) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT uq_infotime_pu_email UNIQUE (id_tenacidade, email)
);

CREATE TABLE IF NOT EXISTS public.infotime_portal_acesso_log (
  id_portal_acesso_log int8 GENERATED BY DEFAULT AS IDENTITY (
    INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE
  ) NOT NULL,
  id_tenacidade int8 NOT NULL,
  id_portal_usuario int8 NOT NULL,
  id_usuario_auditoria int8 NULL,
  data_acesso timestamptz NOT NULL DEFAULT now(),
  ip varchar(45) NULL,
  user_agent varchar(500) NULL,
  acao_realizada varchar(30) NOT NULL,
  id_recurso int8 NULL,
  tipo_recurso varchar(50) NULL,
  endereco_ip_auditoria varchar(50) NULL,
  nome_aplicacao_auditoria varchar(255) NULL,
  CONSTRAINT infotime_portal_log_pkey PRIMARY KEY (id_portal_acesso_log),
  CONSTRAINT fk_infotime_pl_ten FOREIGN KEY (id_tenacidade)
    REFERENCES public.infotime_tenacidade (id_tenacidade) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT fk_infotime_pl_pu FOREIGN KEY (id_portal_usuario)
    REFERENCES public.infotime_portal_usuario (id_portal_usuario) ON DELETE CASCADE ON UPDATE RESTRICT,
  CONSTRAINT fk_infotime_pl_ua FOREIGN KEY (id_usuario_auditoria)
    REFERENCES public.infotime_usuario (id_usuario) ON DELETE RESTRICT ON UPDATE RESTRICT
);

CREATE INDEX IF NOT EXISTS idx_infotime_pl_pu ON public.infotime_portal_acesso_log (id_portal_usuario, data_acesso DESC);

DO $$
DECLARE
  tbl text;
  r regclass;
BEGIN
  FOREACH tbl IN ARRAY ARRAY['infotime_portal_usuario', 'infotime_portal_acesso_log']
  LOOP
    IF to_regclass('public.' || quote_ident(tbl)) IS NULL THEN
      CONTINUE;
    END IF;
    r := ('public.' || tbl)::regclass;
    EXECUTE format('ALTER TABLE %s ENABLE ROW LEVEL SECURITY', r);
    EXECUTE format('ALTER TABLE %s FORCE ROW LEVEL SECURITY', r);
    EXECUTE format('DROP POLICY IF EXISTS %I ON %s', tbl || '_tenant_rls', r);
    EXECUTE format(
      $exec$
      CREATE POLICY %I ON %s
      FOR ALL
      USING (
        NULLIF(current_setting('app.current_tenant_id', true), '') IS NOT NULL
        AND id_tenacidade = (NULLIF(current_setting('app.current_tenant_id', true), ''))::bigint
      )
      WITH CHECK (
        NULLIF(current_setting('app.current_tenant_id', true), '') IS NOT NULL
        AND id_tenacidade = (NULLIF(current_setting('app.current_tenant_id', true), ''))::bigint
      )
      $exec$,
      tbl || '_tenant_rls',
      r
    );
  END LOOP;
END $$;

DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'LigaDev') THEN
    EXECUTE 'GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO "LigaDev"';
    EXECUTE 'GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO "LigaDev"';
  END IF;
  IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'liga_infolab_rw') THEN
    EXECUTE 'GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO liga_infolab_rw';
    EXECUTE 'GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO liga_infolab_rw';
  END IF;
END $$;
