-- Fatia G — comportamento de pagamento, previsão IA, alertas financeiros. RLS + GRANTs.

CREATE TABLE IF NOT EXISTS public.infotime_cliente_comportamento_pagamento (
  id_cliente_comportamento int8 GENERATED BY DEFAULT AS IDENTITY (
    INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE
  ) NOT NULL,
  id_tenacidade int8 NOT NULL,
  id_cliente int8 NOT NULL,
  id_usuario_auditoria int8 NULL,
  dias_media_atraso numeric(6, 2) NULL,
  dias_desvio_padrao numeric(6, 2) NULL,
  percentual_pagamento_dia numeric(5, 2) NULL,
  percentual_ate_7_dias numeric(5, 2) NULL,
  percentual_ate_30_dias numeric(5, 2) NULL,
  percentual_acima_30_dias numeric(5, 2) NULL,
  ticket_medio_mensal numeric(15, 2) NULL,
  meses_analisados int4 NULL,
  data_calculo timestamptz NOT NULL DEFAULT now(),
  endereco_ip_auditoria varchar(50) NULL,
  nome_aplicacao_auditoria varchar(255) NULL,
  CONSTRAINT infotime_cli_comp_pkey PRIMARY KEY (id_cliente_comportamento),
  CONSTRAINT fk_infotime_ccp_ten FOREIGN KEY (id_tenacidade)
    REFERENCES public.infotime_tenacidade (id_tenacidade) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT fk_infotime_ccp_cli FOREIGN KEY (id_cliente)
    REFERENCES public.infotime_cliente (id_cliente) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT fk_infotime_ccp_ua FOREIGN KEY (id_usuario_auditoria)
    REFERENCES public.infotime_usuario (id_usuario) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT uq_infotime_ccp UNIQUE (id_tenacidade, id_cliente)
);

CREATE TABLE IF NOT EXISTS public.infotime_previsao_caixa_ia (
  id_previsao_caixa_ia int8 GENERATED BY DEFAULT AS IDENTITY (
    INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE
  ) NOT NULL,
  id_tenacidade int8 NOT NULL,
  id_usuario_auditoria int8 NULL,
  data_geracao timestamptz NOT NULL DEFAULT now(),
  horizonte_dias int4 NOT NULL,
  valor_projetado numeric(15, 2) NULL,
  valor_projetado_otimista numeric(15, 2) NULL,
  valor_projetado_pessimista numeric(15, 2) NULL,
  confianca_percentual numeric(5, 2) NULL,
  narrativa_ia text NULL,
  alertas_ia jsonb NULL,
  input_tokens int4 NULL,
  output_tokens int4 NULL,
  modelo_usado varchar(50) NULL,
  endereco_ip_auditoria varchar(50) NULL,
  nome_aplicacao_auditoria varchar(255) NULL,
  CONSTRAINT infotime_prev_ia_pkey PRIMARY KEY (id_previsao_caixa_ia),
  CONSTRAINT fk_infotime_pia_ten FOREIGN KEY (id_tenacidade)
    REFERENCES public.infotime_tenacidade (id_tenacidade) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT fk_infotime_pia_ua FOREIGN KEY (id_usuario_auditoria)
    REFERENCES public.infotime_usuario (id_usuario) ON DELETE RESTRICT ON UPDATE RESTRICT
);

CREATE INDEX IF NOT EXISTS idx_infotime_pia_td ON public.infotime_previsao_caixa_ia (id_tenacidade, data_geracao DESC);

CREATE TABLE IF NOT EXISTS public.infotime_alerta_financeiro (
  id_alerta_financeiro int8 GENERATED BY DEFAULT AS IDENTITY (
    INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE
  ) NOT NULL,
  id_tenacidade int8 NOT NULL,
  id_usuario_auditoria int8 NULL,
  tipo_alerta varchar(30) NOT NULL,
  severidade varchar(10) NOT NULL,
  descricao text NOT NULL,
  id_lancamento_receita int8 NULL,
  id_lancamento_despesa int8 NULL,
  valor_envolvido numeric(15, 2) NULL,
  status varchar(20) NOT NULL DEFAULT 'ABERTO',
  data_deteccao timestamptz NOT NULL DEFAULT now(),
  data_resolucao timestamptz NULL,
  id_usuario_responsavel int8 NULL,
  observacoes text NULL,
  endereco_ip_auditoria varchar(50) NULL,
  nome_aplicacao_auditoria varchar(255) NULL,
  CONSTRAINT infotime_alerta_fin_pkey PRIMARY KEY (id_alerta_financeiro),
  CONSTRAINT fk_infotime_af_ten FOREIGN KEY (id_tenacidade)
    REFERENCES public.infotime_tenacidade (id_tenacidade) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT fk_infotime_af_ua FOREIGN KEY (id_usuario_auditoria)
    REFERENCES public.infotime_usuario (id_usuario) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT fk_infotime_af_lr FOREIGN KEY (id_lancamento_receita)
    REFERENCES public.infotime_lancamento_receita (id_lancamento_receita) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT fk_infotime_af_ld FOREIGN KEY (id_lancamento_despesa)
    REFERENCES public.infotime_lancamento_despesa (id_lancamento_despesa) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT fk_infotime_af_ur FOREIGN KEY (id_usuario_responsavel)
    REFERENCES public.infotime_usuario (id_usuario) ON DELETE RESTRICT ON UPDATE RESTRICT
);

CREATE INDEX IF NOT EXISTS idx_infotime_af_st ON public.infotime_alerta_financeiro (id_tenacidade, status, data_deteccao DESC);

DO $$
DECLARE
  tbl text;
  r regclass;
BEGIN
  FOREACH tbl IN ARRAY ARRAY[
    'infotime_cliente_comportamento_pagamento',
    'infotime_previsao_caixa_ia',
    'infotime_alerta_financeiro'
  ]
  LOOP
    IF to_regclass('public.' || quote_ident(tbl)) IS NULL THEN
      CONTINUE;
    END IF;
    r := ('public.' || tbl)::regclass;
    EXECUTE format('ALTER TABLE %s ENABLE ROW LEVEL SECURITY', r);
    EXECUTE format('ALTER TABLE %s FORCE ROW LEVEL SECURITY', r);
    EXECUTE format('DROP POLICY IF EXISTS %I ON %s', tbl || '_tenant_rls', r);
    EXECUTE format(
      $exec$
      CREATE POLICY %I ON %s
      FOR ALL
      USING (
        NULLIF(current_setting('app.current_tenant_id', true), '') IS NOT NULL
        AND id_tenacidade = (NULLIF(current_setting('app.current_tenant_id', true), ''))::bigint
      )
      WITH CHECK (
        NULLIF(current_setting('app.current_tenant_id', true), '') IS NOT NULL
        AND id_tenacidade = (NULLIF(current_setting('app.current_tenant_id', true), ''))::bigint
      )
      $exec$,
      tbl || '_tenant_rls',
      r
    );
  END LOOP;
END $$;

DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'LigaDev') THEN
    EXECUTE 'GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO "LigaDev"';
    EXECUTE 'GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO "LigaDev"';
  END IF;
  IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'liga_infolab_rw') THEN
    EXECUTE 'GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO liga_infolab_rw';
    EXECUTE 'GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO liga_infolab_rw';
  END IF;
END $$;
