-- =============================================================================
-- INFOTIME WEB — MÓDULO FINANCEIRO AVANÇADO
-- DDL completo: tabelas novas + alterações em tabelas existentes
-- Versão: 3.0 — maio de 2026
-- =============================================================================
-- Convenções:
--   • Prefixo obrigatório: infotime_
--   • Colunas: snake_case
--   • PKs: GENERATED BY DEFAULT AS IDENTITY
--   • Booleanos: bpchar(1) com 'S'/'N'
--   • Timestamps: timestamptz
--   • Auditoria em toda tabela: id_usuario_auditoria, endereco_ip_auditoria,
--     nome_aplicacao_auditoria
--   • FK pattern: fk_infotime_{tabela}_{campo}
--   • UQ pattern: uq_infotime_{tabela}_{seq}
--   • Index pattern: idx_infotime_{tabela}_{campo}
-- =============================================================================

-- =============================================================================
-- SEÇÃO 1 — TABELAS JÁ CRIADAS (registradas aqui para referência e versionamento)
-- =============================================================================

-- -----------------------------------------------------------------------------
-- 1.1 infotime_regua_cobranca  [JÁ CRIADA]
-- -----------------------------------------------------------------------------
/*
CREATE TABLE public.infotime_regua_cobranca (
    id_regua_cobranca        int8 GENERATED BY DEFAULT AS IDENTITY
                               (INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807
                                START 1 CACHE 1 NO CYCLE) NOT NULL,
    id_tenacidade            int8         NOT NULL,
    id_usuario_auditoria     int8         DEFAULT NULL,
    descricao                varchar(100) NOT NULL,
    ativo                    bpchar(1)    NOT NULL DEFAULT 'S',
    data_criacao             timestamptz  NOT NULL DEFAULT NOW(),
    endereco_ip_auditoria    varchar(50)  DEFAULT NULL,
    nome_aplicacao_auditoria varchar(255) DEFAULT NULL,

    CONSTRAINT regua_cobranca_pkey
        PRIMARY KEY (id_regua_cobranca),
    CONSTRAINT fk_infotime_regua_cobranca_id_tenacidade
        FOREIGN KEY (id_tenacidade)
        REFERENCES public.infotime_tenacidade (id_tenacidade)
        ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT fk_infotime_regua_cobranca_id_usuario_auditoria
        FOREIGN KEY (id_usuario_auditoria)
        REFERENCES public.infotime_usuario (id_usuario)
        ON DELETE RESTRICT ON UPDATE RESTRICT
);
CREATE INDEX idx_infotime_regua_cobranca_id_tenacidade
    ON public.infotime_regua_cobranca USING btree (id_tenacidade);
CREATE INDEX idx_infotime_regua_cobranca_id_usuario_auditoria
    ON public.infotime_regua_cobranca USING btree (id_usuario_auditoria);
*/

-- -----------------------------------------------------------------------------
-- 1.2 infotime_regua_cobranca_etapa  [JÁ CRIADA]
-- -----------------------------------------------------------------------------
/*
CREATE TABLE public.infotime_regua_cobranca_etapa (
    id_regua_cobranca_etapa  int8 GENERATED BY DEFAULT AS IDENTITY
                               (INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807
                                START 1 CACHE 1 NO CYCLE) NOT NULL,
    id_tenacidade            int8         DEFAULT NULL,
    id_regua_cobranca        int8         NOT NULL,
    id_usuario_auditoria     int8         DEFAULT NULL,
    dias_apos_vencimento     int4         NOT NULL,
    canal                    varchar(20)  NOT NULL,
    assunto                  varchar(200) DEFAULT NULL,
    mensagem                 text         NOT NULL,
    ativo                    bpchar(1)    NOT NULL DEFAULT 'S',
    ordem                    int4         NOT NULL,
    endereco_ip_auditoria    varchar(50)  DEFAULT NULL,
    nome_aplicacao_auditoria varchar(255) DEFAULT NULL,

    CONSTRAINT regua_cobranca_etapa_pkey
        PRIMARY KEY (id_regua_cobranca_etapa),
    CONSTRAINT fk_infotime_regua_cobranca_etapa_id_regua_cobranca
        FOREIGN KEY (id_regua_cobranca)
        REFERENCES public.infotime_regua_cobranca (id_regua_cobranca)
        ON DELETE CASCADE ON UPDATE RESTRICT,
    CONSTRAINT fk_infotime_regua_cobranca_etapa_id_usuario_auditoria
        FOREIGN KEY (id_usuario_auditoria)
        REFERENCES public.infotime_usuario (id_usuario)
        ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT uq_infotime_regua_cobranca_etapa_01
        UNIQUE (id_regua_cobranca, dias_apos_vencimento, canal)
);
CREATE INDEX idx_infotime_regua_cobranca_etapa_id_tenacidade
    ON public.infotime_regua_cobranca_etapa USING btree (id_tenacidade);
CREATE INDEX idx_infotime_regua_cobranca_etapa_id_regua_cobranca
    ON public.infotime_regua_cobranca_etapa USING btree (id_regua_cobranca);
CREATE INDEX idx_infotime_regua_cobranca_etapa_id_usuario_auditoria
    ON public.infotime_regua_cobranca_etapa USING btree (id_usuario_auditoria);
*/

-- -----------------------------------------------------------------------------
-- 1.3 infotime_regua_cobranca_regra  [JÁ CRIADA]
-- -----------------------------------------------------------------------------
/*
CREATE TABLE public.infotime_regua_cobranca_regra (
    id_regua_cobranca_regra  int8 GENERATED BY DEFAULT AS IDENTITY
                               (INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807
                                START 1 CACHE 1 NO CYCLE) NOT NULL,
    id_tenacidade            int8          DEFAULT NULL,
    id_regua_cobranca        int8          NOT NULL,
    id_tipo_agente           int8          DEFAULT NULL,
    id_cliente               int8          DEFAULT NULL,
    id_usuario_auditoria     int8          DEFAULT NULL,
    valor_minimo             numeric(15,2) NOT NULL DEFAULT 0,
    prioridade               int4          NOT NULL DEFAULT 1,
    endereco_ip_auditoria    varchar(50)   DEFAULT NULL,
    nome_aplicacao_auditoria varchar(255)  DEFAULT NULL,

    CONSTRAINT regua_cobranca_regra_pkey
        PRIMARY KEY (id_regua_cobranca_regra),
    CONSTRAINT fk_infotime_regua_cobranca_regra_id_regua_cobranca
        FOREIGN KEY (id_regua_cobranca)
        REFERENCES public.infotime_regua_cobranca (id_regua_cobranca)
        ON DELETE CASCADE ON UPDATE RESTRICT,
    CONSTRAINT fk_infotime_regua_cobranca_regra_id_tipo_agente
        FOREIGN KEY (id_tipo_agente)
        REFERENCES public.infotime_tipo_agente (id_tipo_agente)
        ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT fk_infotime_regua_cobranca_regra_id_cliente
        FOREIGN KEY (id_cliente)
        REFERENCES public.infotime_cliente (id_cliente)
        ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT fk_infotime_regua_cobranca_regra_id_usuario_auditoria
        FOREIGN KEY (id_usuario_auditoria)
        REFERENCES public.infotime_usuario (id_usuario)
        ON DELETE RESTRICT ON UPDATE RESTRICT
);
CREATE INDEX idx_infotime_regua_cobranca_regra_id_tenacidade
    ON public.infotime_regua_cobranca_regra USING btree (id_tenacidade);
CREATE INDEX idx_infotime_regua_cobranca_regra_id_regua_cobranca
    ON public.infotime_regua_cobranca_regra USING btree (id_regua_cobranca);
CREATE INDEX idx_infotime_regua_cobranca_regra_id_usuario_auditoria
    ON public.infotime_regua_cobranca_regra USING btree (id_usuario_auditoria);
*/

-- -----------------------------------------------------------------------------
-- 1.4 infotime_regua_cobranca_envio  [JÁ CRIADA]
-- -----------------------------------------------------------------------------
/*
CREATE TABLE public.infotime_regua_cobranca_envio (
    id_regua_cobranca_envio  int8 GENERATED BY DEFAULT AS IDENTITY
                               (INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807
                                START 1 CACHE 1 NO CYCLE) NOT NULL,
    id_tenacidade            int8         DEFAULT NULL,
    id_lancamento_receita    int8         NOT NULL,
    id_regua_cobranca_etapa  int8         NOT NULL,
    id_usuario_auditoria     int8         DEFAULT NULL,
    data_envio               timestamptz  NOT NULL DEFAULT NOW(),
    status_envio             varchar(20)  NOT NULL DEFAULT 'ENVIADO',
    destinatario             varchar(200) DEFAULT NULL,
    resposta_api             text         DEFAULT NULL,
    tentativas               int4         NOT NULL DEFAULT 1,
    endereco_ip_auditoria    varchar(50)  DEFAULT NULL,
    nome_aplicacao_auditoria varchar(255) DEFAULT NULL,

    CONSTRAINT regua_cobranca_envio_pkey
        PRIMARY KEY (id_regua_cobranca_envio),
    CONSTRAINT fk_infotime_regua_cobranca_envio_id_lancamento_receita
        FOREIGN KEY (id_lancamento_receita)
        REFERENCES public.infotime_lancamento_receita (id_lancamento_receita)
        ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT fk_infotime_regua_cobranca_envio_id_regua_cobranca_etapa
        FOREIGN KEY (id_regua_cobranca_etapa)
        REFERENCES public.infotime_regua_cobranca_etapa (id_regua_cobranca_etapa)
        ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT fk_infotime_regua_cobranca_envio_id_usuario_auditoria
        FOREIGN KEY (id_usuario_auditoria)
        REFERENCES public.infotime_usuario (id_usuario)
        ON DELETE RESTRICT ON UPDATE RESTRICT
);
CREATE INDEX idx_infotime_regua_cobranca_envio_id_tenacidade
    ON public.infotime_regua_cobranca_envio USING btree (id_tenacidade);
CREATE INDEX idx_infotime_regua_cobranca_envio_id_lancamento_receita
    ON public.infotime_regua_cobranca_envio USING btree (id_lancamento_receita);
CREATE INDEX idx_infotime_regua_cobranca_envio_data_envio
    ON public.infotime_regua_cobranca_envio USING btree (data_envio DESC);
CREATE INDEX idx_infotime_regua_cobranca_envio_status_envio
    ON public.infotime_regua_cobranca_envio USING btree (status_envio);
CREATE INDEX idx_infotime_regua_cobranca_envio_id_usuario_auditoria
    ON public.infotime_regua_cobranca_envio USING btree (id_usuario_auditoria);
*/


-- =============================================================================
-- SEÇÃO 2 — ALTERAÇÕES EM TABELAS EXISTENTES (executar nesta ordem)
-- =============================================================================

-- -----------------------------------------------------------------------------
-- 2.1 infotime_plano_conta — colunas de classificação contábil
--     Sprint 1 — necessário para DRE, DFC e Balanço
-- -----------------------------------------------------------------------------
ALTER TABLE public.infotime_plano_conta
    ADD COLUMN IF NOT EXISTS natureza_dre   varchar(30) DEFAULT NULL,
    ADD COLUMN IF NOT EXISTS natureza_dfc   varchar(30) DEFAULT NULL,
    ADD COLUMN IF NOT EXISTS grupo_contabil varchar(30) DEFAULT NULL,
    ADD COLUMN IF NOT EXISTS classificador  varchar(20) DEFAULT NULL;

COMMENT ON COLUMN public.infotime_plano_conta.natureza_dre IS
    'Classificação DRE: RECEITA_BRUTA | DEDUCAO | CUSTO_VARIAVEL | CUSTO_FIXO | DESPESA_FINANCEIRA | OUTRAS_RECEITAS | NAO_APLICAVEL';
COMMENT ON COLUMN public.infotime_plano_conta.natureza_dfc IS
    'Classificação DFC: OPERACIONAL | INVESTIMENTO | FINANCIAMENTO | NAO_CAIXA';
COMMENT ON COLUMN public.infotime_plano_conta.grupo_contabil IS
    'Grupo do balanço: ATIVO_CIRCULANTE | ATIVO_NAO_CIRCULANTE | ATIVO_IMOBILIZADO | ATIVO_INTANGIVEL | PASSIVO_CIRCULANTE | PASSIVO_NAO_CIRCULANTE | CAPITAL_SOCIAL | RESERVAS | LUCROS_ACUMULADOS | RESULTADO_EXERCICIO';
COMMENT ON COLUMN public.infotime_plano_conta.classificador IS
    'Classificador contábil hierárquico ex: 1.1.01, 2.2.03';

CREATE INDEX IF NOT EXISTS idx_infotime_plano_conta_natureza_dre
    ON public.infotime_plano_conta USING btree (natureza_dre)
    WHERE natureza_dre IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_infotime_plano_conta_natureza_dfc
    ON public.infotime_plano_conta USING btree (natureza_dfc)
    WHERE natureza_dfc IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_infotime_plano_conta_grupo_contabil
    ON public.infotime_plano_conta USING btree (grupo_contabil)
    WHERE grupo_contabil IS NOT NULL;

-- -----------------------------------------------------------------------------
-- 2.2 infotime_conta_caixa — flag de composição do DFC
--     Sprint 7 — necessário para DFC
-- -----------------------------------------------------------------------------
ALTER TABLE public.infotime_conta_caixa
    ADD COLUMN IF NOT EXISTS compoe_saldo_dfc bpchar(1) NOT NULL DEFAULT 'S';

COMMENT ON COLUMN public.infotime_conta_caixa.compoe_saldo_dfc IS
    '''S'' = conta bancária/caixa que compõe o saldo inicial/final do DFC. ''N'' = conta de controle interno.';

-- -----------------------------------------------------------------------------
-- 2.3 infotime_cliente — score de inadimplência desnormalizado
--     Sprint 4 — necessário para Score de inadimplência
-- -----------------------------------------------------------------------------
ALTER TABLE public.infotime_cliente
    ADD COLUMN IF NOT EXISTS score_inadimplencia numeric(5,2) DEFAULT NULL,
    ADD COLUMN IF NOT EXISTS classificacao_score  varchar(10)  DEFAULT NULL;

COMMENT ON COLUMN public.infotime_cliente.score_inadimplencia IS
    'Score calculado semanalmente: 0 (alto risco) a 100 (bom pagador)';
COMMENT ON COLUMN public.infotime_cliente.classificacao_score IS
    'VERDE (80-100) | AMARELO (50-79) | VERMELHO (0-49)';

CREATE INDEX IF NOT EXISTS idx_infotime_cliente_score_inadimplencia
    ON public.infotime_cliente USING btree (score_inadimplencia)
    WHERE score_inadimplencia IS NOT NULL;

-- -----------------------------------------------------------------------------
-- 2.4 Indexes de performance em tabelas de lançamento
--     Sprint 1 — melhora queries de aging, DRE e cockpit
-- -----------------------------------------------------------------------------
CREATE INDEX IF NOT EXISTS idx_infotime_lancamento_receita_tenant_data_prev
    ON public.infotime_lancamento_receita USING btree (id_tenacidade, data_previsao)
    WHERE id_situacao_documento NOT IN (4, 24);

CREATE INDEX IF NOT EXISTS idx_infotime_lancamento_receita_tenant_competencia
    ON public.infotime_lancamento_receita USING btree (id_tenacidade, data_competencia);

CREATE INDEX IF NOT EXISTS idx_infotime_lancamento_receita_plano_conta
    ON public.infotime_lancamento_receita USING btree (id_plano_conta);

CREATE INDEX IF NOT EXISTS idx_infotime_lancamento_despesa_tenant_data_prev
    ON public.infotime_lancamento_despesa USING btree (id_tenacidade, data_previsao)
    WHERE id_situacao_documento NOT IN (4);

CREATE INDEX IF NOT EXISTS idx_infotime_lancamento_despesa_tenant_competencia
    ON public.infotime_lancamento_despesa USING btree (id_tenacidade, data_competencia);

CREATE INDEX IF NOT EXISTS idx_infotime_lancamento_despesa_plano_conta
    ON public.infotime_lancamento_despesa USING btree (id_plano_conta);


-- =============================================================================
-- SEÇÃO 3 — TIER 1: TABELAS NOVAS (Sprint 3)
-- =============================================================================

-- -----------------------------------------------------------------------------
-- 3.1 infotime_exame_custo
--     Custo padrão por tipo de exame por competência
--     Sprint 3 — Margem por convênio e custo real por exame
-- -----------------------------------------------------------------------------
CREATE TABLE public.infotime_exame_custo (
    id_exame_custo           int8 GENERATED BY DEFAULT AS IDENTITY
                               (INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807
                                START 1 CACHE 1 NO CYCLE) NOT NULL,
    id_tenacidade            int8          NOT NULL,
    id_usuario_auditoria     int8          DEFAULT NULL,
    codigo_exame             varchar(50)   NOT NULL,
    descricao_exame          varchar(200)  NOT NULL,
    custo_reagente           numeric(10,4) NOT NULL DEFAULT 0,
    custo_material           numeric(10,4) NOT NULL DEFAULT 0,
    custo_mao_obra           numeric(10,4) NOT NULL DEFAULT 0,
    custo_total              numeric(10,4) GENERATED ALWAYS AS
                               (custo_reagente + custo_material + custo_mao_obra) STORED,
    competencia_inicio        date          NOT NULL,
    competencia_fim           date          DEFAULT NULL, -- NULL = vigente
    data_atualizacao         timestamptz   NOT NULL DEFAULT NOW(),
    endereco_ip_auditoria    varchar(50)   DEFAULT NULL,
    nome_aplicacao_auditoria varchar(255)  DEFAULT NULL,

    CONSTRAINT exame_custo_pkey
        PRIMARY KEY (id_exame_custo),
    CONSTRAINT fk_infotime_exame_custo_id_tenacidade
        FOREIGN KEY (id_tenacidade)
        REFERENCES public.infotime_tenacidade (id_tenacidade)
        ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT fk_infotime_exame_custo_id_usuario_auditoria
        FOREIGN KEY (id_usuario_auditoria)
        REFERENCES public.infotime_usuario (id_usuario)
        ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT chk_infotime_exame_custo_custos_positivos
        CHECK (custo_reagente >= 0 AND custo_material >= 0 AND custo_mao_obra >= 0),
    CONSTRAINT chk_infotime_exame_custo_competencia
        CHECK (competencia_fim IS NULL OR competencia_fim > competencia_inicio)
);

CREATE UNIQUE INDEX uq_infotime_exame_custo_01
    ON public.infotime_exame_custo USING btree (id_tenacidade, codigo_exame, competencia_inicio);

CREATE INDEX idx_infotime_exame_custo_id_tenacidade
    ON public.infotime_exame_custo USING btree (id_tenacidade, competencia_inicio DESC);

CREATE INDEX idx_infotime_exame_custo_id_usuario_auditoria
    ON public.infotime_exame_custo USING btree (id_usuario_auditoria);


-- =============================================================================
-- SEÇÃO 4 — TIER 2: TABELAS NOVAS (Sprints 4-8)
-- =============================================================================

-- -----------------------------------------------------------------------------
-- 4.1 infotime_cliente_score
--     Cache do score de inadimplência calculado semanalmente
--     Sprint 4
-- -----------------------------------------------------------------------------
CREATE TABLE public.infotime_cliente_score (
    id_cliente_score         int8 GENERATED BY DEFAULT AS IDENTITY
                               (INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807
                                START 1 CACHE 1 NO CYCLE) NOT NULL,
    id_tenacidade            int8          NOT NULL,
    id_cliente               int8          NOT NULL,
    id_usuario_auditoria     int8          DEFAULT NULL,
    score                    numeric(5,2)  NOT NULL,
    classificacao            varchar(10)   NOT NULL, -- 'VERDE' | 'AMARELO' | 'VERMELHO'
    dia_medio_atraso         numeric(6,2)  DEFAULT NULL,
    desvio_padrao_atraso     numeric(6,2)  DEFAULT NULL,
    percentual_em_atraso     numeric(5,2)  DEFAULT NULL,
    qtd_lancamentos_6m       int4          DEFAULT NULL,
    qtd_atrasados_6m         int4          DEFAULT NULL,
    maior_atraso_6m          int4          DEFAULT NULL,
    valor_medio_mensal       numeric(15,2) DEFAULT NULL,
    data_calculo             timestamptz   NOT NULL DEFAULT NOW(),
    data_proximo_calculo     timestamptz   DEFAULT NULL,
    endereco_ip_auditoria    varchar(50)   DEFAULT NULL,
    nome_aplicacao_auditoria varchar(255)  DEFAULT NULL,

    CONSTRAINT cliente_score_pkey
        PRIMARY KEY (id_cliente_score),
    CONSTRAINT uq_infotime_cliente_score_01
        UNIQUE (id_tenacidade, id_cliente),
    CONSTRAINT chk_infotime_cliente_score_range
        CHECK (score BETWEEN 0 AND 100),
    CONSTRAINT fk_infotime_cliente_score_id_tenacidade
        FOREIGN KEY (id_tenacidade)
        REFERENCES public.infotime_tenacidade (id_tenacidade)
        ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT fk_infotime_cliente_score_id_cliente
        FOREIGN KEY (id_cliente)
        REFERENCES public.infotime_cliente (id_cliente)
        ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT fk_infotime_cliente_score_id_usuario_auditoria
        FOREIGN KEY (id_usuario_auditoria)
        REFERENCES public.infotime_usuario (id_usuario)
        ON DELETE RESTRICT ON UPDATE RESTRICT
);

CREATE INDEX idx_infotime_cliente_score_id_tenacidade
    ON public.infotime_cliente_score USING btree (id_tenacidade);

CREATE INDEX idx_infotime_cliente_score_id_cliente
    ON public.infotime_cliente_score USING btree (id_tenacidade, id_cliente);

CREATE INDEX idx_infotime_cliente_score_classificacao
    ON public.infotime_cliente_score USING btree (id_tenacidade, classificacao, score);

CREATE INDEX idx_infotime_cliente_score_id_usuario_auditoria
    ON public.infotime_cliente_score USING btree (id_usuario_auditoria);

-- -----------------------------------------------------------------------------
-- 4.2 infotime_extrato_bancario_lote
--     Cabeçalho de cada importação de extrato OFX/CSV
--     Sprint 5 — Conciliação bancária
-- -----------------------------------------------------------------------------
CREATE TABLE public.infotime_extrato_bancario_lote (
    id_extrato_bancario_lote int8 GENERATED BY DEFAULT AS IDENTITY
                               (INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807
                                START 1 CACHE 1 NO CYCLE) NOT NULL,
    id_tenacidade            int8          NOT NULL,
    id_conta_caixa           int8          NOT NULL,
    id_usuario_auditoria     int8          DEFAULT NULL,
    data_importacao          timestamptz   NOT NULL DEFAULT NOW(),
    nome_arquivo             varchar(255)  DEFAULT NULL,
    formato_arquivo          varchar(10)   NOT NULL, -- 'OFX' | 'OFXV2' | 'CSV'
    data_inicio_periodo      date          NOT NULL,
    data_fim_periodo         date          NOT NULL,
    total_creditos           numeric(15,2) DEFAULT NULL,
    total_debitos            numeric(15,2) DEFAULT NULL,
    qtd_movimentos           int4          DEFAULT NULL,
    qtd_conciliados_auto     int4          NOT NULL DEFAULT 0,
    qtd_conciliados_manual   int4          NOT NULL DEFAULT 0,
    qtd_pendentes            int4          NOT NULL DEFAULT 0,
    endereco_ip_auditoria    varchar(50)   DEFAULT NULL,
    nome_aplicacao_auditoria varchar(255)  DEFAULT NULL,

    CONSTRAINT extrato_bancario_lote_pkey
        PRIMARY KEY (id_extrato_bancario_lote),
    CONSTRAINT chk_infotime_extrato_bancario_lote_periodo
        CHECK (data_fim_periodo >= data_inicio_periodo),
    CONSTRAINT fk_infotime_extrato_bancario_lote_id_tenacidade
        FOREIGN KEY (id_tenacidade)
        REFERENCES public.infotime_tenacidade (id_tenacidade)
        ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT fk_infotime_extrato_bancario_lote_id_conta_caixa
        FOREIGN KEY (id_conta_caixa)
        REFERENCES public.infotime_conta_caixa (id_conta_caixa)
        ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT fk_infotime_extrato_bancario_lote_id_usuario_auditoria
        FOREIGN KEY (id_usuario_auditoria)
        REFERENCES public.infotime_usuario (id_usuario)
        ON DELETE RESTRICT ON UPDATE RESTRICT
);

CREATE INDEX idx_infotime_extrato_bancario_lote_id_tenacidade
    ON public.infotime_extrato_bancario_lote USING btree (id_tenacidade);

CREATE INDEX idx_infotime_extrato_bancario_lote_id_conta_caixa
    ON public.infotime_extrato_bancario_lote USING btree (id_conta_caixa);

CREATE INDEX idx_infotime_extrato_bancario_lote_data_importacao
    ON public.infotime_extrato_bancario_lote USING btree (data_importacao DESC);

CREATE INDEX idx_infotime_extrato_bancario_lote_id_usuario_auditoria
    ON public.infotime_extrato_bancario_lote USING btree (id_usuario_auditoria);

-- -----------------------------------------------------------------------------
-- 4.3 infotime_extrato_bancario_linha
--     Cada movimento individual do extrato bancário importado
--     Sprint 5 — Conciliação bancária
-- -----------------------------------------------------------------------------
CREATE TABLE public.infotime_extrato_bancario_linha (
    id_extrato_bancario_linha int8 GENERATED BY DEFAULT AS IDENTITY
                                (INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807
                                 START 1 CACHE 1 NO CYCLE) NOT NULL,
    id_extrato_bancario_lote  int8          NOT NULL,
    id_tenacidade             int8          DEFAULT NULL,
    id_usuario_auditoria      int8          DEFAULT NULL,
    data_movimento            date          NOT NULL,
    valor                     numeric(15,2) NOT NULL, -- positivo=crédito, negativo=débito
    tipo                      varchar(10)   NOT NULL, -- 'CREDITO' | 'DEBITO'
    historico_banco           varchar(500)  DEFAULT NULL,
    numero_documento_banco    varchar(100)  DEFAULT NULL,
    cnpj_contraparte          varchar(18)   DEFAULT NULL,
    status_conciliacao        varchar(25)   NOT NULL DEFAULT 'PENDENTE',
                                            -- 'PENDENTE' | 'CONCILIADO_AUTO'
                                            -- | 'CONCILIADO_MANUAL' | 'IGNORADO'
    id_lancamento_receita     int8          DEFAULT NULL,
    id_lancamento_despesa     int8          DEFAULT NULL,
    confianca_match           numeric(5,2)  DEFAULT NULL, -- 0–100%
    data_conciliacao          timestamptz   DEFAULT NULL,
    observacao                varchar(500)  DEFAULT NULL,
    endereco_ip_auditoria     varchar(50)   DEFAULT NULL,
    nome_aplicacao_auditoria  varchar(255)  DEFAULT NULL,

    CONSTRAINT extrato_bancario_linha_pkey
        PRIMARY KEY (id_extrato_bancario_linha),
    CONSTRAINT fk_infotime_extrato_bancario_linha_id_lote
        FOREIGN KEY (id_extrato_bancario_lote)
        REFERENCES public.infotime_extrato_bancario_lote (id_extrato_bancario_lote)
        ON DELETE CASCADE ON UPDATE RESTRICT,
    CONSTRAINT fk_infotime_extrato_bancario_linha_id_lancamento_receita
        FOREIGN KEY (id_lancamento_receita)
        REFERENCES public.infotime_lancamento_receita (id_lancamento_receita)
        ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT fk_infotime_extrato_bancario_linha_id_lancamento_despesa
        FOREIGN KEY (id_lancamento_despesa)
        REFERENCES public.infotime_lancamento_despesa (id_lancamento_despesa)
        ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT fk_infotime_extrato_bancario_linha_id_usuario_auditoria
        FOREIGN KEY (id_usuario_auditoria)
        REFERENCES public.infotime_usuario (id_usuario)
        ON DELETE RESTRICT ON UPDATE RESTRICT
);

CREATE INDEX idx_infotime_extrato_bancario_linha_id_lote
    ON public.infotime_extrato_bancario_linha USING btree (id_extrato_bancario_lote);

CREATE INDEX idx_infotime_extrato_bancario_linha_status
    ON public.infotime_extrato_bancario_linha USING btree (status_conciliacao);

CREATE INDEX idx_infotime_extrato_bancario_linha_data
    ON public.infotime_extrato_bancario_linha USING btree (data_movimento);

CREATE INDEX idx_infotime_extrato_bancario_linha_valor
    ON public.infotime_extrato_bancario_linha USING btree (valor);

CREATE INDEX idx_infotime_extrato_bancario_linha_receita
    ON public.infotime_extrato_bancario_linha USING btree (id_lancamento_receita)
    WHERE id_lancamento_receita IS NOT NULL;

CREATE INDEX idx_infotime_extrato_bancario_linha_despesa
    ON public.infotime_extrato_bancario_linha USING btree (id_lancamento_despesa)
    WHERE id_lancamento_despesa IS NOT NULL;

CREATE INDEX idx_infotime_extrato_bancario_linha_id_usuario_auditoria
    ON public.infotime_extrato_bancario_linha USING btree (id_usuario_auditoria);

-- -----------------------------------------------------------------------------
-- 4.4 infotime_pix_configuracao
--     Credenciais PIX por conta caixa (armazenar client_secret criptografado)
--     Sprint 6 — PIX integrado
-- -----------------------------------------------------------------------------
CREATE TABLE public.infotime_pix_configuracao (
    id_pix_configuracao      int8 GENERATED BY DEFAULT AS IDENTITY
                               (INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807
                                START 1 CACHE 1 NO CYCLE) NOT NULL,
    id_tenacidade            int8         NOT NULL,
    id_conta_caixa           int8         NOT NULL,
    id_usuario_auditoria     int8         DEFAULT NULL,
    ambiente                 varchar(10)  NOT NULL, -- 'PRODUCAO' | 'SANDBOX'
    client_id                varchar(255) NOT NULL,
    client_secret            text         NOT NULL, -- armazenar criptografado AES-256
    chave_pix                varchar(100) NOT NULL, -- EVP, CNPJ, e-mail ou telefone
    banco                    varchar(50)  NOT NULL, -- 'INTER' | 'SICOOB' | 'ITAU' | 'BB'
    certificado_pem          text         DEFAULT NULL, -- mTLS para Inter/Sicoob
    ativo                    bpchar(1)    NOT NULL DEFAULT 'S',
    data_cadastro            timestamptz  NOT NULL DEFAULT NOW(),
    endereco_ip_auditoria    varchar(50)  DEFAULT NULL,
    nome_aplicacao_auditoria varchar(255) DEFAULT NULL,

    CONSTRAINT pix_configuracao_pkey
        PRIMARY KEY (id_pix_configuracao),
    CONSTRAINT uq_infotime_pix_configuracao_01
        UNIQUE (id_conta_caixa),
    CONSTRAINT fk_infotime_pix_configuracao_id_tenacidade
        FOREIGN KEY (id_tenacidade)
        REFERENCES public.infotime_tenacidade (id_tenacidade)
        ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT fk_infotime_pix_configuracao_id_conta_caixa
        FOREIGN KEY (id_conta_caixa)
        REFERENCES public.infotime_conta_caixa (id_conta_caixa)
        ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT fk_infotime_pix_configuracao_id_usuario_auditoria
        FOREIGN KEY (id_usuario_auditoria)
        REFERENCES public.infotime_usuario (id_usuario)
        ON DELETE RESTRICT ON UPDATE RESTRICT
);

CREATE INDEX idx_infotime_pix_configuracao_id_tenacidade
    ON public.infotime_pix_configuracao USING btree (id_tenacidade);

CREATE INDEX idx_infotime_pix_configuracao_id_conta_caixa
    ON public.infotime_pix_configuracao USING btree (id_conta_caixa);

CREATE INDEX idx_infotime_pix_configuracao_id_usuario_auditoria
    ON public.infotime_pix_configuracao USING btree (id_usuario_auditoria);

-- -----------------------------------------------------------------------------
-- 4.5 infotime_pix_cobranca
--     Cobranças PIX geradas e rastreamento de pagamentos via webhook
--     Sprint 6 — PIX integrado
-- -----------------------------------------------------------------------------
CREATE TABLE public.infotime_pix_cobranca (
    id_pix_cobranca          int8 GENERATED BY DEFAULT AS IDENTITY
                               (INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807
                                START 1 CACHE 1 NO CYCLE) NOT NULL,
    id_tenacidade            int8          NOT NULL,
    id_lancamento_receita    int8          DEFAULT NULL,
    id_usuario_auditoria     int8          DEFAULT NULL,
    tx_id                    varchar(35)   NOT NULL,  -- identificador único PIX (BACEN)
    e2e_id                   varchar(32)   DEFAULT NULL, -- preenchido no pagamento
    valor                    numeric(15,2) NOT NULL,
    status                   varchar(40)   NOT NULL DEFAULT 'ATIVA',
                                           -- 'ATIVA' | 'CONCLUIDA'
                                           -- | 'REMOVIDA_PELO_USUARIO_RECEBEDOR'
                                           -- | 'REMOVIDA_PELO_PSP'
    qr_code                  text          DEFAULT NULL, -- payload EMV
    imagem_qr_code           text          DEFAULT NULL, -- PNG base64
    data_criacao             timestamptz   NOT NULL DEFAULT NOW(),
    data_vencimento          date          DEFAULT NULL,
    data_pagamento           timestamptz   DEFAULT NULL,
    valor_pago               numeric(15,2) DEFAULT NULL,
    cnpj_pagador             varchar(18)   DEFAULT NULL,
    nome_pagador             varchar(200)  DEFAULT NULL,
    info_pagador             text          DEFAULT NULL,
    webhook_payload          jsonb         DEFAULT NULL, -- payload bruto para auditoria
    tentativas_consulta      int4          NOT NULL DEFAULT 0,
    endereco_ip_auditoria    varchar(50)   DEFAULT NULL,
    nome_aplicacao_auditoria varchar(255)  DEFAULT NULL,

    CONSTRAINT pix_cobranca_pkey
        PRIMARY KEY (id_pix_cobranca),
    CONSTRAINT uq_infotime_pix_cobranca_tx_id
        UNIQUE (tx_id),
    CONSTRAINT fk_infotime_pix_cobranca_id_tenacidade
        FOREIGN KEY (id_tenacidade)
        REFERENCES public.infotime_tenacidade (id_tenacidade)
        ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT fk_infotime_pix_cobranca_id_lancamento_receita
        FOREIGN KEY (id_lancamento_receita)
        REFERENCES public.infotime_lancamento_receita (id_lancamento_receita)
        ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT fk_infotime_pix_cobranca_id_usuario_auditoria
        FOREIGN KEY (id_usuario_auditoria)
        REFERENCES public.infotime_usuario (id_usuario)
        ON DELETE RESTRICT ON UPDATE RESTRICT
);

CREATE UNIQUE INDEX idx_infotime_pix_cobranca_tx_id
    ON public.infotime_pix_cobranca USING btree (tx_id);

CREATE INDEX idx_infotime_pix_cobranca_status
    ON public.infotime_pix_cobranca USING btree (status);

CREATE INDEX idx_infotime_pix_cobranca_id_lancamento_receita
    ON public.infotime_pix_cobranca USING btree (id_lancamento_receita)
    WHERE id_lancamento_receita IS NOT NULL;

CREATE INDEX idx_infotime_pix_cobranca_id_tenacidade
    ON public.infotime_pix_cobranca USING btree (id_tenacidade, data_criacao DESC);

CREATE INDEX idx_infotime_pix_cobranca_id_usuario_auditoria
    ON public.infotime_pix_cobranca USING btree (id_usuario_auditoria);

-- -----------------------------------------------------------------------------
-- 4.6 infotime_portal_usuario
--     Usuários do portal self-service de convênios (auth separada do sistema)
--     Sprint 8 — Portal do convênio
-- -----------------------------------------------------------------------------
CREATE TABLE public.infotime_portal_usuario (
    id_portal_usuario        int8 GENERATED BY DEFAULT AS IDENTITY
                               (INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807
                                START 1 CACHE 1 NO CYCLE) NOT NULL,
    id_tenacidade            int8         NOT NULL,
    id_cliente               int8         NOT NULL,
    id_usuario_auditoria     int8         DEFAULT NULL,
    email                    varchar(200) NOT NULL,
    senha_hash               varchar(255) NOT NULL, -- bcrypt custo 12
    nome_contato             varchar(200) DEFAULT NULL,
    ativo                    bpchar(1)    NOT NULL DEFAULT 'S',
    data_cadastro            timestamptz  NOT NULL DEFAULT NOW(),
    ultimo_acesso            timestamptz  DEFAULT NULL,
    token_reset_senha        varchar(100) DEFAULT NULL,
    validade_token_reset     timestamptz  DEFAULT NULL,
    tentativas_login         int4         NOT NULL DEFAULT 0,
    bloqueado_ate            timestamptz  DEFAULT NULL,
    endereco_ip_auditoria    varchar(50)  DEFAULT NULL,
    nome_aplicacao_auditoria varchar(255) DEFAULT NULL,

    CONSTRAINT portal_usuario_pkey
        PRIMARY KEY (id_portal_usuario),
    CONSTRAINT uq_infotime_portal_usuario_01
        UNIQUE (id_tenacidade, email),
    CONSTRAINT fk_infotime_portal_usuario_id_tenacidade
        FOREIGN KEY (id_tenacidade)
        REFERENCES public.infotime_tenacidade (id_tenacidade)
        ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT fk_infotime_portal_usuario_id_cliente
        FOREIGN KEY (id_cliente)
        REFERENCES public.infotime_cliente (id_cliente)
        ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT fk_infotime_portal_usuario_id_usuario_auditoria
        FOREIGN KEY (id_usuario_auditoria)
        REFERENCES public.infotime_usuario (id_usuario)
        ON DELETE RESTRICT ON UPDATE RESTRICT
);

CREATE INDEX idx_infotime_portal_usuario_id_tenacidade
    ON public.infotime_portal_usuario USING btree (id_tenacidade);

CREATE INDEX idx_infotime_portal_usuario_id_cliente
    ON public.infotime_portal_usuario USING btree (id_cliente);

CREATE INDEX idx_infotime_portal_usuario_id_usuario_auditoria
    ON public.infotime_portal_usuario USING btree (id_usuario_auditoria);

-- -----------------------------------------------------------------------------
-- 4.7 infotime_portal_acesso_log
--     Log de auditoria de todas as ações no portal do convênio
--     Sprint 8 — Portal do convênio
-- -----------------------------------------------------------------------------
CREATE TABLE public.infotime_portal_acesso_log (
    id_portal_acesso_log     int8 GENERATED BY DEFAULT AS IDENTITY
                               (INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807
                                START 1 CACHE 1 NO CYCLE) NOT NULL,
    id_portal_usuario        int8         NOT NULL,
    id_tenacidade            int8         DEFAULT NULL,
    id_usuario_auditoria     int8         DEFAULT NULL,
    data_acesso              timestamptz  NOT NULL DEFAULT NOW(),
    ip                       varchar(45)  DEFAULT NULL, -- suporta IPv6
    user_agent               varchar(500) DEFAULT NULL,
    acao                     varchar(50)  NOT NULL,
                                          -- 'LOGIN' | 'LOGOUT' | 'VER_FATURA'
                                          -- | 'GERAR_PIX' | 'BAIXAR_NF'
                                          -- | 'VER_HISTORICO' | 'RESET_SENHA'
    endereco_ip_auditoria    varchar(50)  DEFAULT NULL,
    nome_aplicacao_auditoria varchar(255) DEFAULT NULL,

    CONSTRAINT portal_acesso_log_pkey
        PRIMARY KEY (id_portal_acesso_log),
    CONSTRAINT fk_infotime_portal_acesso_log_id_portal_usuario
        FOREIGN KEY (id_portal_usuario)
        REFERENCES public.infotime_portal_usuario (id_portal_usuario)
        ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT fk_infotime_portal_acesso_log_id_usuario_auditoria
        FOREIGN KEY (id_usuario_auditoria)
        REFERENCES public.infotime_usuario (id_usuario)
        ON DELETE RESTRICT ON UPDATE RESTRICT
);

CREATE INDEX idx_infotime_portal_acesso_log_id_portal_usuario
    ON public.infotime_portal_acesso_log USING btree (id_portal_usuario, data_acesso DESC);

CREATE INDEX idx_infotime_portal_acesso_log_data_acesso
    ON public.infotime_portal_acesso_log USING btree (data_acesso DESC);

CREATE INDEX idx_infotime_portal_acesso_log_id_tenacidade
    ON public.infotime_portal_acesso_log USING btree (id_tenacidade);

CREATE INDEX idx_infotime_portal_acesso_log_id_usuario_auditoria
    ON public.infotime_portal_acesso_log USING btree (id_usuario_auditoria);

-- -----------------------------------------------------------------------------
-- 4.8 infotime_conta_saldo
--     Saldos de abertura por plano de conta e competência (base do balanço)
--     Sprint 7 — Balanço patrimonial e DFC
-- -----------------------------------------------------------------------------
CREATE TABLE public.infotime_conta_saldo (
    id_conta_saldo           int8 GENERATED BY DEFAULT AS IDENTITY
                               (INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807
                                START 1 CACHE 1 NO CYCLE) NOT NULL,
    id_tenacidade            int8          NOT NULL,
    id_plano_conta           int8          NOT NULL,
    id_usuario_auditoria     int8          DEFAULT NULL,
    competencia              date          NOT NULL, -- sempre primeiro dia do mês
    saldo_inicial            numeric(15,2) NOT NULL DEFAULT 0,
    saldo_final              numeric(15,2) DEFAULT NULL, -- calculado no fechamento
    data_fechamento          timestamptz   DEFAULT NULL,
    endereco_ip_auditoria    varchar(50)   DEFAULT NULL,
    nome_aplicacao_auditoria varchar(255)  DEFAULT NULL,

    CONSTRAINT conta_saldo_pkey
        PRIMARY KEY (id_conta_saldo),
    CONSTRAINT uq_infotime_conta_saldo_01
        UNIQUE (id_tenacidade, id_plano_conta, competencia),
    CONSTRAINT chk_infotime_conta_saldo_dia1
        CHECK (EXTRACT(DAY FROM competencia) = 1),
    CONSTRAINT fk_infotime_conta_saldo_id_tenacidade
        FOREIGN KEY (id_tenacidade)
        REFERENCES public.infotime_tenacidade (id_tenacidade)
        ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT fk_infotime_conta_saldo_id_plano_conta
        FOREIGN KEY (id_plano_conta)
        REFERENCES public.infotime_plano_conta (id_plano_conta)
        ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT fk_infotime_conta_saldo_id_usuario_auditoria
        FOREIGN KEY (id_usuario_auditoria)
        REFERENCES public.infotime_usuario (id_usuario)
        ON DELETE RESTRICT ON UPDATE RESTRICT
);

CREATE INDEX idx_infotime_conta_saldo_id_tenacidade
    ON public.infotime_conta_saldo USING btree (id_tenacidade, competencia DESC);

CREATE INDEX idx_infotime_conta_saldo_id_plano_conta
    ON public.infotime_conta_saldo USING btree (id_plano_conta);

CREATE INDEX idx_infotime_conta_saldo_id_usuario_auditoria
    ON public.infotime_conta_saldo USING btree (id_usuario_auditoria);

-- -----------------------------------------------------------------------------
-- 4.9 infotime_lancamento_contabil
--     Partidas dobradas — geradas automaticamente a partir de receitas/despesas
--     e manualmente para ajustes patrimoniais
--     Sprint 7 — Balanço patrimonial e DFC
-- -----------------------------------------------------------------------------
CREATE TABLE public.infotime_lancamento_contabil (
    id_lancamento_contabil   int8 GENERATED BY DEFAULT AS IDENTITY
                               (INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807
                                START 1 CACHE 1 NO CYCLE) NOT NULL,
    id_tenacidade            int8          NOT NULL,
    id_usuario_auditoria     int8          DEFAULT NULL,
    data_lancamento          date          NOT NULL,
    historico_contabil       varchar(500)  DEFAULT NULL,
    id_documento_origem      int8          DEFAULT NULL,
    tipo_documento_origem    varchar(30)   DEFAULT NULL,
                                           -- 'LANCAMENTO_RECEITA' | 'LANCAMENTO_DESPESA'
                                           -- | 'AJUSTE_MANUAL' | 'ABERTURA'
    id_conta_debito          int8          NOT NULL,
    id_conta_credito         int8          NOT NULL,
    valor                    numeric(15,2) NOT NULL,
    estornado                bpchar(1)     NOT NULL DEFAULT 'N',
    id_lancamento_estorno    int8          DEFAULT NULL,
    data_criacao             timestamptz   NOT NULL DEFAULT NOW(),
    endereco_ip_auditoria    varchar(50)   DEFAULT NULL,
    nome_aplicacao_auditoria varchar(255)  DEFAULT NULL,

    CONSTRAINT lancamento_contabil_pkey
        PRIMARY KEY (id_lancamento_contabil),
    CONSTRAINT chk_infotime_lancamento_contabil_contas_distintas
        CHECK (id_conta_debito <> id_conta_credito),
    CONSTRAINT chk_infotime_lancamento_contabil_valor_positivo
        CHECK (valor > 0),
    CONSTRAINT fk_infotime_lancamento_contabil_id_tenacidade
        FOREIGN KEY (id_tenacidade)
        REFERENCES public.infotime_tenacidade (id_tenacidade)
        ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT fk_infotime_lancamento_contabil_id_conta_debito
        FOREIGN KEY (id_conta_debito)
        REFERENCES public.infotime_plano_conta (id_plano_conta)
        ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT fk_infotime_lancamento_contabil_id_conta_credito
        FOREIGN KEY (id_conta_credito)
        REFERENCES public.infotime_plano_conta (id_plano_conta)
        ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT fk_infotime_lancamento_contabil_id_estorno
        FOREIGN KEY (id_lancamento_estorno)
        REFERENCES public.infotime_lancamento_contabil (id_lancamento_contabil)
        ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT fk_infotime_lancamento_contabil_id_usuario_auditoria
        FOREIGN KEY (id_usuario_auditoria)
        REFERENCES public.infotime_usuario (id_usuario)
        ON DELETE RESTRICT ON UPDATE RESTRICT
);

CREATE INDEX idx_infotime_lancamento_contabil_data
    ON public.infotime_lancamento_contabil USING btree (data_lancamento);

CREATE INDEX idx_infotime_lancamento_contabil_id_conta_debito
    ON public.infotime_lancamento_contabil USING btree (id_conta_debito);

CREATE INDEX idx_infotime_lancamento_contabil_id_conta_credito
    ON public.infotime_lancamento_contabil USING btree (id_conta_credito);

CREATE INDEX idx_infotime_lancamento_contabil_id_tenacidade
    ON public.infotime_lancamento_contabil USING btree (id_tenacidade, data_lancamento);

CREATE INDEX idx_infotime_lancamento_contabil_origem
    ON public.infotime_lancamento_contabil USING btree (tipo_documento_origem, id_documento_origem)
    WHERE id_documento_origem IS NOT NULL;

CREATE INDEX idx_infotime_lancamento_contabil_id_usuario_auditoria
    ON public.infotime_lancamento_contabil USING btree (id_usuario_auditoria);


-- =============================================================================
-- SEÇÃO 5 — TIER 3: TABELAS NOVAS (Sprint 9+)
-- =============================================================================

-- -----------------------------------------------------------------------------
-- 5.1 infotime_cliente_comportamento_pagamento
--     Comportamento histórico de pagamento — base para previsão IA
--     Sprint 9 — Previsão de caixa com IA
-- -----------------------------------------------------------------------------
CREATE TABLE public.infotime_cliente_comportamento_pagamento (
    id_cliente_comportamento  int8 GENERATED BY DEFAULT AS IDENTITY
                                (INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807
                                 START 1 CACHE 1 NO CYCLE) NOT NULL,
    id_tenacidade             int8          NOT NULL,
    id_cliente                int8          NOT NULL,
    id_usuario_auditoria      int8          DEFAULT NULL,
    dias_media_atraso         numeric(6,2)  DEFAULT NULL,
    dias_desvio_padrao        numeric(6,2)  DEFAULT NULL,
    percentual_pagamento_dia  numeric(5,2)  DEFAULT NULL, -- % que paga no dia ou antes
    percentual_ate_7_dias     numeric(5,2)  DEFAULT NULL,
    percentual_ate_30_dias    numeric(5,2)  DEFAULT NULL,
    percentual_acima_30_dias  numeric(5,2)  DEFAULT NULL,
    ticket_medio_mensal       numeric(15,2) DEFAULT NULL,
    meses_analisados          int4          DEFAULT NULL,
    data_calculo              timestamptz   NOT NULL DEFAULT NOW(),
    endereco_ip_auditoria     varchar(50)   DEFAULT NULL,
    nome_aplicacao_auditoria  varchar(255)  DEFAULT NULL,

    CONSTRAINT cliente_comportamento_pagamento_pkey
        PRIMARY KEY (id_cliente_comportamento),
    CONSTRAINT uq_infotime_cliente_comportamento_01
        UNIQUE (id_tenacidade, id_cliente),
    CONSTRAINT fk_infotime_cliente_comportamento_id_tenacidade
        FOREIGN KEY (id_tenacidade)
        REFERENCES public.infotime_tenacidade (id_tenacidade)
        ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT fk_infotime_cliente_comportamento_id_cliente
        FOREIGN KEY (id_cliente)
        REFERENCES public.infotime_cliente (id_cliente)
        ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT fk_infotime_cliente_comportamento_id_usuario_auditoria
        FOREIGN KEY (id_usuario_auditoria)
        REFERENCES public.infotime_usuario (id_usuario)
        ON DELETE RESTRICT ON UPDATE RESTRICT
);

CREATE INDEX idx_infotime_cliente_comportamento_id_tenacidade
    ON public.infotime_cliente_comportamento_pagamento USING btree
    (id_tenacidade, data_calculo DESC);

CREATE INDEX idx_infotime_cliente_comportamento_id_cliente
    ON public.infotime_cliente_comportamento_pagamento USING btree (id_cliente);

CREATE INDEX idx_infotime_cliente_comportamento_id_usuario_auditoria
    ON public.infotime_cliente_comportamento_pagamento USING btree (id_usuario_auditoria);

-- -----------------------------------------------------------------------------
-- 5.2 infotime_previsao_caixa_ia
--     Cache de projeções de caixa geradas pelo Claude API (TTL ~24h)
--     Sprint 9 — Previsão de caixa com IA
-- -----------------------------------------------------------------------------
CREATE TABLE public.infotime_previsao_caixa_ia (
    id_previsao_caixa_ia        int8 GENERATED BY DEFAULT AS IDENTITY
                                  (INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807
                                   START 1 CACHE 1 NO CYCLE) NOT NULL,
    id_tenacidade               int8          NOT NULL,
    id_usuario_auditoria        int8          DEFAULT NULL,
    data_geracao                timestamptz   NOT NULL DEFAULT NOW(),
    horizonte_dias              int4          NOT NULL,   -- 30 | 60 | 90
    valor_projetado             numeric(15,2) DEFAULT NULL,
    valor_projetado_otimista    numeric(15,2) DEFAULT NULL,
    valor_projetado_pessimista  numeric(15,2) DEFAULT NULL,
    confianca_percentual        numeric(5,2)  DEFAULT NULL,
    narrativa_ia                text          DEFAULT NULL,
    alertas_ia                  jsonb         DEFAULT NULL, -- array de strings
    input_tokens                int4          DEFAULT NULL,
    output_tokens               int4          DEFAULT NULL,
    modelo_usado                varchar(60)   NOT NULL DEFAULT 'claude-sonnet-4-20250514',
    custo_usd                   numeric(8,6)  DEFAULT NULL,
    endereco_ip_auditoria       varchar(50)   DEFAULT NULL,
    nome_aplicacao_auditoria    varchar(255)  DEFAULT NULL,

    CONSTRAINT previsao_caixa_ia_pkey
        PRIMARY KEY (id_previsao_caixa_ia),
    CONSTRAINT fk_infotime_previsao_caixa_ia_id_tenacidade
        FOREIGN KEY (id_tenacidade)
        REFERENCES public.infotime_tenacidade (id_tenacidade)
        ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT fk_infotime_previsao_caixa_ia_id_usuario_auditoria
        FOREIGN KEY (id_usuario_auditoria)
        REFERENCES public.infotime_usuario (id_usuario)
        ON DELETE RESTRICT ON UPDATE RESTRICT
);

CREATE INDEX idx_infotime_previsao_caixa_ia_id_tenacidade
    ON public.infotime_previsao_caixa_ia USING btree (id_tenacidade, data_geracao DESC);

CREATE INDEX idx_infotime_previsao_caixa_ia_id_usuario_auditoria
    ON public.infotime_previsao_caixa_ia USING btree (id_usuario_auditoria);

-- -----------------------------------------------------------------------------
-- 5.3 infotime_alerta_financeiro
--     Alertas automáticos de anomalias detectadas nos lançamentos
--     Sprint 9 — Detecção de anomalias financeiras
-- -----------------------------------------------------------------------------
CREATE TABLE public.infotime_alerta_financeiro (
    id_alerta_financeiro     int8 GENERATED BY DEFAULT AS IDENTITY
                               (INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807
                                START 1 CACHE 1 NO CYCLE) NOT NULL,
    id_tenacidade            int8          NOT NULL,
    id_usuario_auditoria     int8          DEFAULT NULL,
    tipo_alerta              varchar(60)   NOT NULL,
                                           -- 'VALOR_ANOMALO_FORNECEDOR'
                                           -- | 'PAGAMENTO_DUPLICADO_SUSPEITO'
                                           -- | 'FORNECEDOR_NOVO_ALTO_VALOR'
                                           -- | 'VALOR_RECEBIDO_DIVERGENTE'
                                           -- | 'LANCAMENTO_HORARIO_SUSPEITO'
    severidade               varchar(10)   NOT NULL,  -- 'BAIXA' | 'MEDIA' | 'ALTA'
    descricao                text          NOT NULL,
    id_lancamento_receita    int8          DEFAULT NULL,
    id_lancamento_despesa    int8          DEFAULT NULL,
    valor_envolvido          numeric(15,2) DEFAULT NULL,
    valor_referencia         numeric(15,2) DEFAULT NULL,
    desvio_percentual        numeric(8,2)  DEFAULT NULL,
    status                   varchar(25)   NOT NULL DEFAULT 'ABERTO',
                                           -- 'ABERTO' | 'INVESTIGANDO'
                                           -- | 'FALSO_POSITIVO' | 'CONFIRMADO' | 'RESOLVIDO'
    data_deteccao            timestamptz   NOT NULL DEFAULT NOW(),
    data_resolucao           timestamptz   DEFAULT NULL,
    id_usuario_responsavel   int8          DEFAULT NULL,
    observacoes              text          DEFAULT NULL,
    endereco_ip_auditoria    varchar(50)   DEFAULT NULL,
    nome_aplicacao_auditoria varchar(255)  DEFAULT NULL,

    CONSTRAINT alerta_financeiro_pkey
        PRIMARY KEY (id_alerta_financeiro),
    CONSTRAINT fk_infotime_alerta_financeiro_id_tenacidade
        FOREIGN KEY (id_tenacidade)
        REFERENCES public.infotime_tenacidade (id_tenacidade)
        ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT fk_infotime_alerta_financeiro_id_lancamento_receita
        FOREIGN KEY (id_lancamento_receita)
        REFERENCES public.infotime_lancamento_receita (id_lancamento_receita)
        ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT fk_infotime_alerta_financeiro_id_lancamento_despesa
        FOREIGN KEY (id_lancamento_despesa)
        REFERENCES public.infotime_lancamento_despesa (id_lancamento_despesa)
        ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT fk_infotime_alerta_financeiro_id_usuario_auditoria
        FOREIGN KEY (id_usuario_auditoria)
        REFERENCES public.infotime_usuario (id_usuario)
        ON DELETE RESTRICT ON UPDATE RESTRICT
);

CREATE INDEX idx_infotime_alerta_financeiro_id_tenacidade
    ON public.infotime_alerta_financeiro USING btree (id_tenacidade, data_deteccao DESC);

CREATE INDEX idx_infotime_alerta_financeiro_status
    ON public.infotime_alerta_financeiro USING btree (status, data_deteccao DESC);

CREATE INDEX idx_infotime_alerta_financeiro_severidade
    ON public.infotime_alerta_financeiro USING btree (id_tenacidade, severidade, status);

CREATE INDEX idx_infotime_alerta_financeiro_id_usuario_auditoria
    ON public.infotime_alerta_financeiro USING btree (id_usuario_auditoria);


-- =============================================================================
-- FIM DO SCRIPT
-- =============================================================================
-- Resumo:
--   Seção 1 — 4 tabelas JÁ CRIADAS (comentadas para referência)
--   Seção 2 — ALTER TABLE em 3 tabelas existentes + 8 indexes de performance
--   Seção 3 — 1 tabela nova (Tier 1): infotime_exame_custo
--   Seção 4 — 9 tabelas novas (Tier 2): cliente_score, extrato_bancario_lote,
--             extrato_bancario_linha, pix_configuracao, pix_cobranca,
--             portal_usuario, portal_acesso_log, conta_saldo,
--             lancamento_contabil
--   Seção 5 — 3 tabelas novas (Tier 3): cliente_comportamento_pagamento,
--             previsao_caixa_ia, alerta_financeiro
--
-- Total de tabelas a criar neste script: 13 (executar em ordem)
-- Total de tabelas já existentes:        4  (seção 1 comentada)
-- Total de tabelas alteradas:            3  (seção 2)
-- =============================================================================
