-- Fatia F — saldos por conta e lançamentos contábeis (partidas dobradas). RLS + GRANTs.

CREATE TABLE IF NOT EXISTS public.infotime_conta_saldo (
  id_conta_saldo int8 GENERATED BY DEFAULT AS IDENTITY (
    INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE
  ) NOT NULL,
  id_tenacidade int8 NOT NULL,
  id_plano_conta int8 NOT NULL,
  id_usuario_auditoria int8 NULL,
  competencia date NOT NULL,
  saldo_inicial numeric(15, 2) NOT NULL DEFAULT 0,
  saldo_final numeric(15, 2) NULL,
  data_fechamento timestamptz NULL,
  endereco_ip_auditoria varchar(50) NULL,
  nome_aplicacao_auditoria varchar(255) NULL,
  CONSTRAINT infotime_conta_saldo_pkey PRIMARY KEY (id_conta_saldo),
  CONSTRAINT fk_infotime_cs_ten FOREIGN KEY (id_tenacidade)
    REFERENCES public.infotime_tenacidade (id_tenacidade) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT fk_infotime_cs_pc FOREIGN KEY (id_plano_conta)
    REFERENCES public.infotime_plano_conta (id_plano_conta) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT fk_infotime_cs_ua FOREIGN KEY (id_usuario_auditoria)
    REFERENCES public.infotime_usuario (id_usuario) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT uq_infotime_cs UNIQUE (id_tenacidade, id_plano_conta, competencia)
);

CREATE TABLE IF NOT EXISTS public.infotime_lancamento_contabil (
  id_lancamento_contabil int8 GENERATED BY DEFAULT AS IDENTITY (
    INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE
  ) NOT NULL,
  id_tenacidade int8 NOT NULL,
  id_usuario_auditoria int8 NULL,
  data_lancamento date NOT NULL,
  historico_contabil varchar(500) NULL,
  id_documento_origem int8 NULL,
  tipo_documento_origem varchar(30) NULL,
  id_plano_conta_debito int8 NOT NULL,
  id_plano_conta_credito int8 NOT NULL,
  valor numeric(15, 2) NOT NULL,
  data_criacao timestamptz NOT NULL DEFAULT now(),
  id_usuario_criacao int8 NULL,
  endereco_ip_auditoria varchar(50) NULL,
  nome_aplicacao_auditoria varchar(255) NULL,
  CONSTRAINT infotime_lanc_cont_pkey PRIMARY KEY (id_lancamento_contabil),
  CONSTRAINT fk_infotime_lc_ten FOREIGN KEY (id_tenacidade)
    REFERENCES public.infotime_tenacidade (id_tenacidade) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT fk_infotime_lc_ua FOREIGN KEY (id_usuario_auditoria)
    REFERENCES public.infotime_usuario (id_usuario) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT fk_infotime_lc_db FOREIGN KEY (id_plano_conta_debito)
    REFERENCES public.infotime_plano_conta (id_plano_conta) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT fk_infotime_lc_cr FOREIGN KEY (id_plano_conta_credito)
    REFERENCES public.infotime_plano_conta (id_plano_conta) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT fk_infotime_lc_uc FOREIGN KEY (id_usuario_criacao)
    REFERENCES public.infotime_usuario (id_usuario) ON DELETE RESTRICT ON UPDATE RESTRICT
);

CREATE INDEX IF NOT EXISTS idx_infotime_lc_data ON public.infotime_lancamento_contabil (data_lancamento);
CREATE INDEX IF NOT EXISTS idx_infotime_lc_db ON public.infotime_lancamento_contabil (id_plano_conta_debito);
CREATE INDEX IF NOT EXISTS idx_infotime_lc_cr ON public.infotime_lancamento_contabil (id_plano_conta_credito);
CREATE INDEX IF NOT EXISTS idx_infotime_lc_orig ON public.infotime_lancamento_contabil (tipo_documento_origem, id_documento_origem);

DO $$
DECLARE
  tbl text;
  r regclass;
BEGIN
  FOREACH tbl IN ARRAY ARRAY['infotime_conta_saldo', 'infotime_lancamento_contabil']
  LOOP
    IF to_regclass('public.' || quote_ident(tbl)) IS NULL THEN
      CONTINUE;
    END IF;
    r := ('public.' || tbl)::regclass;
    EXECUTE format('ALTER TABLE %s ENABLE ROW LEVEL SECURITY', r);
    EXECUTE format('ALTER TABLE %s FORCE ROW LEVEL SECURITY', r);
    EXECUTE format('DROP POLICY IF EXISTS %I ON %s', tbl || '_tenant_rls', r);
    EXECUTE format(
      $exec$
      CREATE POLICY %I ON %s
      FOR ALL
      USING (
        NULLIF(current_setting('app.current_tenant_id', true), '') IS NOT NULL
        AND id_tenacidade = (NULLIF(current_setting('app.current_tenant_id', true), ''))::bigint
      )
      WITH CHECK (
        NULLIF(current_setting('app.current_tenant_id', true), '') IS NOT NULL
        AND id_tenacidade = (NULLIF(current_setting('app.current_tenant_id', true), ''))::bigint
      )
      $exec$,
      tbl || '_tenant_rls',
      r
    );
  END LOOP;
END $$;

DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'LigaDev') THEN
    EXECUTE 'GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO "LigaDev"';
    EXECUTE 'GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO "LigaDev"';
  END IF;
  IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'liga_infolab_rw') THEN
    EXECUTE 'GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO liga_infolab_rw';
    EXECUTE 'GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO liga_infolab_rw';
  END IF;
END $$;
